Elasticity: Stress and Strain
-----------------------------

::: {#import-auto-id0000032 .learning-objectives depth="1"}
### Learning Objectives { data-type="title"}

By the end of this section, you will be able to:

-   State Hooke\'s law.
-   Explain Hooke\'s law using graphical representation between
    deformation and applied force.
-   Discuss the three types of deformations such as changes in length,
    sideways shear, and changes in volume.
-   Describe with examples the Young\'s modulus, shear modulus, and bulk
    modulus.
-   Determine the change in length given mass, length, and radius.
:::

We now move from consideration of forces that affect the motion of an
object (such as friction and drag) to those that affect an object\'s
shape. If a bulldozer pushes a car into a wall, the car will not move
but it will noticeably change shape. A change in shape due to the
application of a force is a [deformation]{data-type="term"}. Even very
small forces are known to cause some deformation. For small
deformations, two important characteristics are observed. First, the
object returns to its original shape when the force is removed---that
is, the deformation is elastic for small deformations. Second, the size
of the deformation is proportional to the force---that is, for small
deformations, Hooke\'s law is obeyed. In equation form, [Hooke\'s
law]{data-type="term"} is given by

::: {#eip-940 data-type="equation"}
$${{F = k\Delta L},}{}$$
:::

where ${\Delta L}{}$ is the amount of deformation (the change in length,
for example) produced by the force
$F{}$*`<!-- no-selfclose -->`{=html}*, and $k{}$ is a proportionality
constant that depends on the shape and composition of the object and the
direction of the force. Note that this force is a function of the
deformation ${\Delta L}{}$ ---it is not constant as a kinetic friction
force is. Rearranging this to

::: {#eip-72 data-type="equation"}
$${\Delta L = \frac{F}{k}}{}$$
:::

makes it clear that the deformation is proportional to the applied
force. [link](#import-auto-id1165298678464){.autogenerated-content}
shows the Hooke\'s law relationship between the extension ${\Delta L}{}$
of a spring or of a human bone. For metals or springs, the straight line
region in which Hooke\'s law pertains is much larger. Bones are brittle
and the elastic region is small and the fracture abrupt. Eventually a
large enough stress to the material will cause it to break or fracture.

::: {#fs-id1165298979850 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Hooke\'s Law
:::

::: {#eip-319 data-type="equation"}
$${F = {k\Delta L}},{}$$
:::

where ${\Delta L}{}$ is the amount of deformation (the change in length,
for example) produced by the force
$F{}$*`<!-- no-selfclose -->`{=html}*, and $k{}$ is a proportionality
constant that depends on the shape and composition of the object and the
direction of the force.

::: {#eip-516 data-type="equation"}
$${\Delta L = \frac{F}{k}}{}$$
:::
:::

![A graph of deformation ${\Delta L}{}$ versus applied force $F{}$. The
straight segment is the linear region where Hooke\'s law is obeyed. The
slope of the straight region is $\frac{1}{k}{}$. For larger forces, the
graph is curved but the deformation is still elastic--- ${\Delta L}{}$
will return to zero if the force is removed. Still greater forces
permanently deform the object until it finally fractures. The shape of
the curve near fracture depends on several factors, including how the
force $F{}$ is applied. Note that in this graph the slope increases just
before fracture, indicating that a small increase in $F{}$ is producing
a large increase in $L{}$ near the
fracture.](images/Figure_06_03_01a.jpg){#import-auto-id1165298678464}

The proportionality constant $k{}$ depends upon a number of factors for
the material. For example, a guitar string made of nylon stretches when
it is tightened, and the elongation ${\Delta L}{}$ is proportional to
the force applied (at least for small deformations). Thicker nylon
strings and ones made of steel stretch less for the same applied force,
implying they have a larger $k{}$ (see
[link](#import-auto-id1165296232089){.autogenerated-content}). Finally,
all three strings return to their normal lengths when the force is
removed, provided the deformation is small. Most materials will behave
in this manner if the deformation is less than about 0.1% or about 1
part in $\text{10}^{3}{}$^`<!-- no-selfclose -->`{=html}^.

![The same force, in this case a weight ($w{}$), applied to three
different guitar strings of identical length produces the three
different deformations shown as shaded segments. The string on the left
is thin nylon, the one in the middle is thicker nylon, and the one on
the right is
steel.](images/Figure_06_03_02a.jpg){#import-auto-id1165296232089}

::: {#fs-id1165298669085 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Stretch Yourself a Little
:::

How would you go about measuring the proportionality constant $k{}$ of a
rubber band? If a rubber band stretched 3 cm when a 100-g mass was
attached to it, then how much would it stretch if two similar rubber
bands were attached to the same mass---even if put together in parallel
or alternatively if tied together in series?
:::

We now consider three specific types of deformations: changes in length
(tension and compression), sideways shear (stress), and changes in
volume. All deformations are assumed to be small unless otherwise
stated.

::: {#fs-id1165298672473 depth="1"}
### Changes in Length---Tension and Compression: Elastic Modulus {#changes-in-lengthtension-and-compression-elastic-modulus data-type="title"}

A change in length ${\Delta L}{}$ is produced when a force is applied to
a wire or rod parallel to its length $L_{0}{}$, either stretching it (a
tension) or compressing it. (See
[link](#import-auto-id1165298469619){.autogenerated-content}.)

![(a) Tension. The rod is stretched a length ${\Delta L}{}$ when a force
is applied parallel to its length. (b) Compression. The same rod is
compressed by forces with the same magnitude in the opposite direction.
For very small deformations and uniform materials, ${\Delta L}{}$ is
approximately the same for the same magnitude of tension or compression.
For larger deformations, the cross-sectional area changes as the rod is
compressed or
stretched.](images/Figure_06_03_03a.jpg){#import-auto-id1165298469619}

Experiments have shown that the change in length (${\Delta L}{}$)
depends on only a few variables. As already noted, ${\Delta L}{}$ is
proportional to the force $F{}$ and depends on the substance from which
the object is made. Additionally, the change in length is proportional
to the original length $L_{0}{}$ and inversely proportional to the
cross-sectional area of the wire or rod. For example, a long guitar
string will stretch more than a short one, and a thick string will
stretch less than a thin one. We can combine all these factors into one
equation for ${\Delta L}{}$:

::: {#eip-511 data-type="equation"}
$${{{\Delta L = \frac{1}{Y}}\frac{F}{A}L_{0}},}{}$$
:::

where ${\Delta L}{}$ is the change in length, $F{}$ the applied force,
*`<!-- no-selfclose -->`{=html}*$Y{}$ is a factor, called the elastic
modulus or Young\'s modulus, that depends on the substance,
*`<!-- no-selfclose -->`{=html}*$A{}$ is the cross-sectional area, and
*`<!-- no-selfclose -->`{=html}*$L_{0}{}$ is the original length.
[link](#import-auto-id1165298671576){.autogenerated-content} lists
values of *$Y{}$* for several materials---those with a large $Y{}$ are
said to have a large [tensile strength]{data-type="term"} because they
deform less for a given tension or compression.

```{=html}
<table id="import-auto-id1165298671576" summary="Table showing Young&#39;s modulus Y, Shear modulus S, and bulk modulus B for a variety of materials.">
```
```{=html}
<caption>
```
[Elastic Moduli[\[footnote\]](#eip-id1325742)]{data-type="title"}
```{=html}
<aside role="doc-footnote" type="footnote" id="eip-id1325742">
```
Approximate and average values. Young\'s moduli $Y{}$ for tension and
compression sometimes differ but are averaged here. Bone has
significantly different Young\'s moduli for tension and compression.
```{=html}
</aside>
```
```{=html}
</caption>
```
```{=html}
<thead>
```
```{=html}
<tr>
```
```{=html}
<th data-align="center">
```
Material
:::

```{=html}
</th>
```
```{=html}
<th data-align="center">
```
Young\'s modulus (tension--compression)*Y*
$(\text{10}^{\text{9}}\ \text{N/m}^{\text{2}})$

```{=html}
</th>
```
```{=html}
<th data-align="center">
```
Shear modulus *S*$(\text{10}^{\text{9}}\ \text{N/m}^{\text{2}})$

```{=html}
</th>
```
```{=html}
<th data-align="center">
```
Bulk modulus *B* $(\text{10}^{\text{9}}\ \text{N/m}^{\text{2}})$

```{=html}
</th>
```
```{=html}
</tr>
```
```{=html}
</thead>
```
```{=html}
<tbody>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Aluminum

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
70

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
25

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
75

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Bone -- tension

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
16

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
80

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
8

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Bone -- compression

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
9

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Brass

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
90

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
35

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
75

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Brick

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
15

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Concrete

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
20

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Glass

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
70

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
20

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
30

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Granite

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
45

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
20

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
45

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Hair (human)

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
10

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Hardwood

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
15

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
10

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Iron, cast

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
100

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
40

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
90

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Lead

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
16

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
5

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
50

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Marble

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
60

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
20

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
70

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Nylon

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
5

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Polystyrene

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
3

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Silk

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
6

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Spider thread

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
3

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Steel

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
210

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
80

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
130

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Tendon

```{=html}
</td>
```
```{=html}
<td data-align="center">
```
1

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Acetone

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td data-align="center">
```
0.7

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Ethanol

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td data-align="center">
```
0.9

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Glycerin

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td data-align="center">
```
4.5

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Mercury

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td data-align="center">
```
25

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Water

```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td>
```
```{=html}
</td>
```
```{=html}
<td data-align="center">
```
2.2

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
</tbody>
```
```{=html}
</table>
```
Young\'s moduli are not listed for liquids and gases in
[link](#import-auto-id1165298671576){.autogenerated-content} because
they cannot be stretched or compressed in only one direction. Note that
there is an assumption that the object does not accelerate, so that
there are actually two applied forces of magnitude $F{}$ acting in
opposite directions. For example, the strings in
[link](#import-auto-id1165298469619){.autogenerated-content} are being
pulled down by a force of magnitude $w{}$ and held up by the ceiling,
which also exerts a force of magnitude $w{}$.

::: {#fs-id1165298667158 data-type="example"}
::: {data-type="title"}
The Stretch of a Long Cable
:::

Suspension cables are used to carry gondolas at ski resorts. (See
[link](#import-auto-id1165298535463){.autogenerated-content}) Consider a
suspension cable that includes an unsupported span of 3020 m. Calculate
the amount of stretch in the steel cable. Assume that the cable has a
diameter of 5.6 cm and the maximum tension it can withstand is
${3\text{.}{0 \times \text{10}^{6}}\ \text{N}}{}$.

![Gondolas travel along suspension cables at the Gala Yuzawa ski resort
in Japan. (credit: Rudy Herman,
Flickr)](images/Figure_06_03_04a.jpg){#import-auto-id1165298535463}

::: {.tinysection}
[Strategy]{data-type="title"}
:::

The force is equal to the maximum tension, or
${{F = 3}\text{.}{0 \times \text{10}^{6}}\ \text{N}}{}$. The
cross-sectional area is
${{{\pi r}^{2} = 2}\text{.}{\text{46} \times \text{10}^{- 3}}\ \text{m}^{2}}{}$.
The equation ${{\Delta L = \frac{1}{Y}}\frac{F}{A}L_{0}}{}$ can be used
to find the change in length.

::: {.tinysection}
[Solution]{data-type="title"}
:::

All quantities are known. Thus,

::: {#eip-657 data-type="equation"}
$$\begin{array}{lll}
{\Delta L} & = & {\left( \frac{1}{{\text{210} \times \text{10}^{9}}\ \text{N/m}^{2}} \right)\left( \frac{3\text{.}{0 \times \text{10}^{6}\ }\text{N}}{2.46 \times \operatorname{10}^{–3}\ \text{m}^{2}} \right)\left( \text{3020\ m} \right)} \\
 & = & {\text{18\ m}.} \\
\end{array}{}$$
:::

::: {.tinysection}
[Discussion]{data-type="title"}
:::

This is quite a stretch, but only about 0.6% of the unsupported length.
Effects of temperature upon length might be important in these
environments.
:::

Bones, on the whole, do not fracture due to tension or compression.
Rather they generally fracture due to sideways impact or bending,
resulting in the bone shearing or snapping. The behavior of bones under
tension and compression is important because it determines the load the
bones can carry. Bones are classified as weight-bearing structures such
as columns in buildings and trees. Weight-bearing structures have
special features; columns in building have steel-reinforcing rods while
trees and bones are fibrous. The bones in different parts of the body
serve different structural functions and are prone to different
stresses. Thus the bone in the top of the femur is arranged in thin
sheets separated by marrow while in other places the bones can be
cylindrical and filled with marrow or just solid. Overweight people have
a tendency toward bone damage due to sustained compressions in bone
joints and tendons.

Another biological example of Hooke\'s law occurs in tendons.
Functionally, the tendon (the tissue connecting muscle to bone) must
stretch easily at first when a force is applied, but offer a much
greater restoring force for a greater strain.
[link](#import-auto-id1165296334455){.autogenerated-content} shows a
stress-strain relationship for a human tendon. Some tendons have a high
collagen content so there is relatively little strain, or length change;
others, like support tendons (as in the leg) can change length up to
10%. Note that this stress-strain curve is nonlinear, since the slope of
the line changes in different regions. In the first part of the stretch
called the toe region, the fibers in the tendon begin to align in the
direction of the stress---this is called *uncrimping*. In the linear
region, the fibrils will be stretched, and in the failure region
individual fibers begin to break. A simple model of this relationship
can be illustrated by springs in parallel: different springs are
activated at different lengths of stretch. Examples of this are given in
the problems at end of this chapter. Ligaments (tissue connecting bone
to bone) behave in a similar way.

![Typical stress-strain curve for mammalian tendon. Three regions are
shown: (1) toe region (2) linear region, and (3) failure
region.](images/Figure_06_03_05_xa.jpg){#import-auto-id1165296334455}

Unlike bones and tendons, which need to be strong as well as elastic,
the arteries and lungs need to be very stretchable. The elastic
properties of the arteries are essential for blood flow. The pressure in
the arteries increases and arterial walls stretch when the blood is
pumped out of the heart. When the aortic valve shuts, the pressure in
the arteries drops and the arterial walls relax to maintain the blood
flow. When you feel your pulse, you are feeling exactly this---the
elastic behavior of the arteries as the blood gushes through with each
pump of the heart. If the arteries were rigid, you would not feel a
pulse. The heart is also an organ with special elastic properties. The
lungs expand with muscular effort when we breathe in but relax freely
and elastically when we breathe out. Our skins are particularly elastic,
especially for the young. A young person can go from 100 kg to 60 kg
with no visible sag in their skins. The elasticity of all organs reduces
with age. Gradual physiological aging through reduction in elasticity
starts in the early 20s.

::: {#fs-id1165296715479 data-type="example"}
::: {data-type="title"}
Calculating Deformation: How Much Does Your Leg Shorten When You Stand
on It?
:::

Calculate the change in length of the upper leg bone (the femur) when a
70.0 kg man supports 62.0 kg of his mass on it, assuming the bone to be
equivalent to a uniform rod that is 40.0 cm long and 2.00 cm in radius.

::: {.tinysection}
[Strategy]{data-type="title"}
:::

The force is equal to the weight supported, or

::: {#eip-843 data-type="equation"}
$${{{{F = \text{mg}} = \left( {\text{62}\text{.}0\ kg} \right)}{\left( {9\text{.}\text{80\ m}\text{/s}^{2}} \right) = \text{607}}\text{.}6\ N},}{}$$
:::

and the cross-sectional area is
${{{\pi r}^{2} = 1}\text{.}\text{257}{\times \text{10}^{- 3}}\ \text{m}^{2}}{}$.
The equation ${{\Delta L = \frac{1}{Y}}\frac{F}{A}L_{0}}{}$ can be used
to find the change in length.

::: {.tinysection}
[Solution]{data-type="title"}
:::

All quantities except ${\Delta L}{}$ are known. Note that the
compression value for Young\'s modulus for bone must be used here. Thus,

::: {#eip-24 data-type="equation"}
$$\begin{array}{lll}
{\Delta L} & = & {\left( \frac{1}{{9 \times \text{10}^{9}}\ \text{N/m}^{2}} \right)\left( \frac{\text{607}\text{.}\text{6\ N}}{1.{\text{257} \times \text{10}^{- 3}\ }\text{m}^{2}} \right)(0\text{.}\text{400\ m})} \\
 & = & {2{\times \text{10}^{-5}}\ \text{m.}} \\
\end{array}{}$$
:::

::: {.tinysection}
[Discussion]{data-type="title"}
:::

This small change in length seems reasonable, consistent with our
experience that bones are rigid. In fact, even the rather large forces
encountered during strenuous physical activity do not compress or bend
bones by large amounts. Although bone is rigid compared with fat or
muscle, several of the substances listed in
[link](#import-auto-id1165298671576){.autogenerated-content} have larger
values of Young\'s modulus $Y{}$. In other words, they are more rigid
and have greater tensile strength.
:::

The equation for change in length is traditionally rearranged and
written in the following form:

::: {#eip-725 data-type="equation"}
$${{\frac{F}{A} = Y}\frac{\Delta L}{L_{0}}}.{}$$
:::

The ratio of force to area, *$\frac{F}{A}{}$*, is defined as
[stress]{#import-auto-id1165298867113 data-type="term"} (measured in
$\text{N/m}^{\text{2}}$), and the ratio of the change in length to
length, $\frac{\Delta L}{L_{0}}{}$, is defined as
[strain]{#import-auto-id1165298883978 data-type="term"} (a unitless
quantity). In other words,

::: {#eip-760 data-type="equation"}
$${\text{stress} = {Y \times \text{strain}}.}{}$$
:::

In this form, the equation is analogous to Hooke\'s law, with stress
analogous to force and strain analogous to deformation. If we again
rearrange this equation to the form

::: {#eip-77 data-type="equation"}
$${{{F = \text{YA}}\frac{\Delta L}{L_{0}}},}{}$$
:::

we see that it is the same as Hooke\'s law with a proportionality
constant

::: {#eip-903 data-type="equation"}
$${{k = \frac{\text{YA}}{L_{0}}}.}{}$$
:::

This general idea---that force and the deformation it causes are
proportional for small deformations---applies to changes in length,
sideways bending, and changes in volume.

::: {#fs-id1165296614220 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Stress
:::

The ratio of force to area, *$\frac{F}{A}{}$*, is defined as stress
measured in N/m^2^.
:::

::: {#fs-id1165298937224 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Strain
:::

The ratio of the change in length to length, $\frac{\Delta L}{L_{0}}{}$,
is defined as strain (a unitless quantity). In other words,

::: {#eip-282 data-type="equation"}
$${\text{stress} = {Y \times \text{strain}}.}{}$$
:::
:::

```{=html}
</section>
```
::: {#fs-id1165298648094 depth="1"}
### Sideways Stress: Shear Modulus {#sideways-stress-shear-modulus data-type="title"}

[link](#import-auto-id1165296375245){.autogenerated-content} illustrates
what is meant by a sideways stress or a *shearing force*. Here the
deformation is called ${\Delta x}{}$ and it is perpendicular to
$L_{0}{}$, rather than parallel as with tension and compression. Shear
deformation behaves similarly to tension and compression and can be
described with similar equations. The expression for [shear
deformation]{#import-auto-id1165296259204 data-type="term"} is

::: {#eip-178 data-type="equation"}
$${{\Delta x = \frac{1}{S}}\frac{F}{A}L_{0}}{},$$
:::

where $S{}$ is the shear modulus (see
[link](#import-auto-id1165298671576){.autogenerated-content}) and $F{}$
is the force applied perpendicular to $L_{0}{}$ and parallel to the
cross-sectional area $A{}$. Again, to keep the object from accelerating,
there are actually two equal and opposite forces $F{}$ applied across
opposite faces, as illustrated in
[link](#import-auto-id1165296375245){.autogenerated-content}. The
equation is logical---for example, it is easier to bend a long thin
pencil (small $A{}$) than a short thick one, and both are more easily
bent than similar steel rods (large $S{}$).

::: {#fs-id1165298835468 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Shear Deformation
:::

::: {#eip-894 data-type="equation"}
$${{{\Delta x = \frac{1}{S}}\frac{F}{A}L_{0}},}{}$$
:::

where $S{}$ is the shear modulus and $F{}$ is the force applied
perpendicular to $L_{0}{}$ and parallel to the cross-sectional area
$A{}$.
:::

![Shearing forces are applied perpendicular to the length $L_{\text{0}}$
and parallel to the area $A$, producing a deformation $\text{Δx}$.
Vertical forces are not shown, but it should be kept in mind that in
addition to the two shearing forces, $\textbf{F}{}$, there must be
supporting forces to keep the object from rotating. The distorting
effects of these supporting forces are ignored in this treatment. The
weight of the object also is not shown, since it is usually negligible
compared with forces large enough to cause significant
deformations.](images/Figure_06_03_06a.jpg){#import-auto-id1165296375245}

Examination of the shear moduli in
[link](#import-auto-id1165298671576){.autogenerated-content} reveals
some telling patterns. For example, shear moduli are less than Young\'s
moduli for most materials. Bone is a remarkable exception. Its shear
modulus is not only greater than its Young\'s modulus, but it is as
large as that of steel. This is one reason that bones can be long and
relatively thin. Bones can support loads comparable to that of concrete
and steel. Most bone fractures are not caused by compression but by
excessive twisting and bending.

The spinal column (consisting of 26 vertebral segments separated by
discs) provides the main support for the head and upper part of the
body. The spinal column has normal curvature for stability, but this
curvature can be increased, leading to increased shearing forces on the
lower vertebrae. Discs are better at withstanding compressional forces
than shear forces. Because the spine is not vertical, the weight of the
upper body exerts some of both. Pregnant women and people that are
overweight (with large abdomens) need to move their shoulders back to
maintain balance, thereby increasing the curvature in their spine and so
increasing the shear component of the stress. An increased angle due to
more curvature increases the shear forces along the plane. These higher
shear forces increase the risk of back injury through ruptured discs.
The lumbosacral disc (the wedge shaped disc below the last vertebrae) is
particularly at risk because of its location.

The shear moduli for concrete and brick are very small; they are too
highly variable to be listed. Concrete used in buildings can withstand
compression, as in pillars and arches, but is very poor against shear,
as might be encountered in heavily loaded floors or during earthquakes.
Modern structures were made possible by the use of steel and
steel-reinforced concrete. Almost by definition, liquids and gases have
shear moduli near zero, because they flow in response to shearing
forces.

::: {#fs-id1165296288315 data-type="example"}
::: {data-type="title"}
Calculating Force Required to Deform: That Nail Does Not Bend Much Under
a Load
:::

Find the mass of the picture hanging from a steel nail as shown in
[link](#import-auto-id1165298644588){.autogenerated-content}, given that
the nail bends only $\text{1.80\ µm}{}$. (Assume the shear modulus is
known to two significant figures.)

![Side view of a nail with a picture hung from it. The nail flexes very
slightly (shown much larger than actual) because of the shearing effect
of the supported weight. Also shown is the upward force of the wall on
the nail, illustrating that there are equal and opposite forces applied
across opposite cross sections of the nail. See
[link](#fs-id1165296288315){.autogenerated-content} for a calculation of
the mass of the
picture.](images/Figure_06_03_08a.jpg){#import-auto-id1165298644588}

::: {.tinysection}
[Strategy]{data-type="title"}
:::

The force $F{}$ on the nail (neglecting the nail\'s own weight) is the
weight of the picture $w{}$. If we can find $w{}$, then the mass of the
picture is just $\frac{w}{g}{}$ . The equation
${{\Delta x = \frac{1}{S}}\frac{F}{A}L_{0}}{}$ can be solved for $F{}$.

::: {.tinysection}
[Solution]{data-type="title"}
:::

Solving the equation ${{\Delta x = \frac{1}{S}}\frac{F}{A}L_{0}}{}$ for
$F$, we see that all other quantities can be found:

::: {#eip-458 data-type="equation"}
$${{{F = \frac{SA}{L_{0}}}\Delta x}.}{}$$
:::

*S* is found in
[link](#import-auto-id1165298671576){.autogenerated-content} and is
${{S = {\text{80} \times \text{10}^{9}}}\ \text{N/m}^{2}}{}$. The radius
$r{}$ is 0.750 mm (as seen in the figure), so the cross-sectional area
is

::: {#eip-365 data-type="equation"}
$${{{{A = {\pi r}^{2}} = 1}\text{.}{\text{77} \times \text{10}^{- 6}}\ \text{m}^{2}}.}{}$$
:::

The value for $L_{0}{}$ is also shown in the figure. Thus,

::: {#eip-736 data-type="equation"}
$${{F = {\frac{({\text{80} \times \text{10}^{9}}\ \text{N/m}^{2})(1\text{.}{\text{77} \times \text{10}^{- 6}\ }\text{m}^{2})}{(5\text{.}{\text{00} \times \text{10}^{- 3}\ }\text{m})}(}}1\text{.}{\text{80} \times \text{10}^{- 6}}\ \text{m}) = \text{51\ N.}}{}$$
:::

This 51 N force is the weight $w$ of the picture, so the picture\'s mass
is

::: {#eip-147 data-type="equation"}
$${{{{{m = \frac{w}{g}} = \frac{F}{g}} = 5}\text{.2\ kg}}.}{}$$
:::

::: {.tinysection}
[Discussion]{data-type="title"}
:::

This is a fairly massive picture, and it is impressive that the nail
flexes only $\text{1.80\ µm}$---an amount undetectable to the unaided
eye.
:::
:::

::: {#fs-id1165298483858 depth="1"}
### Changes in Volume: Bulk Modulus {#changes-in-volume-bulk-modulus data-type="title"}

An object will be compressed in all directions if inward forces are
applied evenly on all its surfaces as in
[link](#import-auto-id1165296230954){.autogenerated-content}. It is
relatively easy to compress gases and extremely difficult to compress
liquids and solids. For example, air in a wine bottle is compressed when
it is corked. But if you try corking a brim-full bottle, you cannot
compress the wine---some must be removed if the cork is to be inserted.
The reason for these different compressibilities is that atoms and
molecules are separated by large empty spaces in gases but packed close
together in liquids and solids. To compress a gas, you must force its
atoms and molecules closer together. To compress liquids and solids, you
must actually compress their atoms and molecules, and very strong
electromagnetic forces in them oppose this compression.

![An inward force on all surfaces compresses this cube. Its change in
volume is proportional to the force per unit area and its original
volume, and is related to the compressibility of the
substance.](images/Figure_06_03_09a.jpg){#import-auto-id1165296230954}

We can describe the compression or volume deformation of an object with
an equation. First, we note that a force "applied evenly" is defined to
have the same stress, or ratio of force to area $\frac{F}{A}{}$ on all
surfaces. The deformation produced is a change in volume ${\Delta V}{}$,
which is found to behave very similarly to the shear, tension, and
compression previously discussed. (This is not surprising, since a
compression of the entire object is equivalent to compressing each of
its three dimensions.) The relationship of the change in volume to other
physical quantities is given by

::: {#eip-63 data-type="equation"}
$${{{\Delta V = \frac{1}{B}}\frac{F}{A}V_{0}},}{}$$
:::

where $B$ is the bulk modulus (see
[link](#import-auto-id1165298671576){.autogenerated-content}), $V_{0}{}$
is the original volume, and *$\frac{F}{A}{}$* is the force per unit area
applied uniformly inward on all surfaces. Note that no bulk moduli are
given for gases.

What are some examples of bulk compression of solids and liquids? One
practical example is the manufacture of industrial-grade diamonds by
compressing carbon with an extremely large force per unit area. The
carbon atoms rearrange their crystalline structure into the more tightly
packed pattern of diamonds. In nature, a similar process occurs deep
underground, where extremely large forces result from the weight of
overlying material. Another natural source of large compressive forces
is the pressure created by the weight of water, especially in deep parts
of the oceans. Water exerts an inward force on all surfaces of a
submerged object, and even on the water itself. At great depths, water
is measurably compressed, as the following example illustrates.

::: {#fs-id1165298751418 data-type="example"}
::: {data-type="title"}
Calculating Change in Volume with Deformation: How Much Is Water
Compressed at Great Ocean Depths?
:::

Calculate the fractional decrease in volume ($\frac{\Delta V}{V_{0}}{}$)
for seawater at 5.00 km depth, where the force per unit area is
${5\text{.}{\text{00} \times \text{10}^{7}}\ {N/m^{2}}}{}$ .

::: {.tinysection}
[Strategy]{data-type="title"}
:::

Equation ${{\Delta V = \frac{1}{B}}\frac{F}{A}V_{0}}{}$ is the correct
physical relationship. All quantities in the equation except
$\frac{\Delta V}{V_{0}}$ are known.

::: {.tinysection}
[Solution]{data-type="title"}
:::

Solving for the unknown $\frac{\Delta V}{V_{0}}$ gives

::: {#eip-646 data-type="equation"}
$${{{\frac{\Delta V}{V_{0}} = \frac{1}{B}}\frac{F}{A}}.}{}$$
:::

Substituting known values with the value for the bulk modulus $B$ from
[link](#import-auto-id1165298671576){.autogenerated-content},

::: {#eip-818 data-type="equation"}
$$\begin{array}{lll}
\frac{\Delta V}{V_{0}} & = & \frac{5.00{\times \text{10}^{7}}\ \text{N/m}^{2}}{2\text{.}{2 \times \text{10}^{9}}\ \text{N/m}^{2}} \\
 & = & {0.023 = 2.3\%.} \\
\end{array}{}$$
:::

::: {.tinysection}
[Discussion]{data-type="title"}
:::

Although measurable, this is not a significant decrease in volume
considering that the force per unit area is about 500 atmospheres (1
million pounds per square foot). Liquids and solids are extraordinarily
difficult to compress.
:::

Conversely, very large forces are created by liquids and solids when
they try to expand but are constrained from doing so---which is
equivalent to compressing them to less than their normal volume. This
often occurs when a contained material warms up, since most materials
expand when their temperature increases. If the materials are tightly
constrained, they deform or break their container. Another very common
example occurs when water freezes. Water, unlike most materials, expands
when it freezes, and it can easily fracture a boulder, rupture a
biological cell, or crack an engine block that gets in its way.

Other types of deformations, such as torsion or twisting, behave
analogously to the tension, shear, and bulk deformations considered
here.
:::

::: {#fs-id1165298595602-summary depth="1"}
### Section Summary { data-type="title"}

-   [Hooke\'s law is given by]{#import-auto-id1165298476009}

    ::: {#eip-149 data-type="equation"}
    $${{F = k\text{Δ}L},}{}$$
    :::

    where ${\Delta L}{}$ is the amount of deformation (the change in
    length), $F{}$ is the applied force, and $k{}$ is a proportionality
    constant that depends on the shape and composition of the object and
    the direction of the force. The relationship between the deformation
    and the applied force can also be written as

    ::: {#eip-556 data-type="equation"}
    $${{{\Delta L = \frac{1}{Y}}\frac{F}{A}L_{0}},}{}$$
    :::

    where *$Y\ {}$`<!-- no-selfclose -->`{=html}* is *Young\'s modulus*,
    which depends on the substance, *$A{}$* is the cross-sectional area,
    and $L_{0}{}$ is the original length.

-   [The ratio of force to area, *$\frac{F}{A}{}$*, is defined as
    *stress*, measured in N/m^2^.]{#import-auto-id1165298686194}

-   [The ratio of the change in length to length,
    $\frac{\Delta L}{L_{0}}{}$, is defined as *strain* (a unitless
    quantity). In other words,]{#import-auto-id1165298726978}
    ::: {#eip-98 data-type="equation"}
    $${\text{stress} = {Y \times \text{strain}}.}{}$$
    :::

-   [The expression for shear deformation
    is]{#import-auto-id1165298586473}

    ::: {#eip-19 data-type="equation"}
    $${{{\Delta x = \frac{1}{S}}\frac{F}{A}L_{0}},}{}$$
    :::

    where $S$ is the shear modulus and $F$ is the force applied
    perpendicular to $L_{\text{0}}$ and parallel to the cross-sectional
    area $A$.

-   [The relationship of the change in volume to other physical
    quantities is given by]{#import-auto-id1165298548492}

    ::: {#eip-492 data-type="equation"}
    $${{{\Delta V = \frac{1}{B}}\frac{F}{A}V_{0}},}{}$$
    :::

    where $B$ is the bulk modulus, $V_{\text{0}}$ is the original
    volume, and $\frac{F}{A}{}$ is the force per unit area applied
    uniformly inward on all surfaces.
:::

::: {#fs-id1165298807240 .conceptual-questions depth="1" element-type="conceptual-questions"}
### Conceptual Questions { data-type="title"}

::: {#fs-id1165298797418 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1165298797419 data-type="problem"}
The elastic properties of the arteries are essential for blood flow.
Explain the importance of this in terms of the characteristics of the
flow of blood (pulsating or continuous).
:::
:::

::: {#fs-id1165298867810 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1165298867811 data-type="problem"}
What are you feeling when you feel your pulse? Measure your pulse rate
for 10 s and for 1 min. Is there a factor of 6 difference?
:::
:::

::: {#fs-id1165296252981 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1165298517998 data-type="problem"}
Examine different types of shoes, including sports shoes and thongs. In
terms of physics, why are the bottom surfaces designed as they are? What
differences will dry and wet conditions make for these surfaces?
:::
:::

::: {#fs-id1165298840083 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1165298840084 data-type="problem"}
Would you expect your height to be different depending upon the time of
day? Why or why not?
:::
:::

::: {#fs-id1165298650751 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1165298619439 data-type="problem"}
Would you expect a large or small stress to be required to deform a
spider web? Why is this elasticity an important feature for a spider
web?
:::
:::

::: {#fs-id1165298550516 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1165298550517 data-type="problem"}
Explain why pregnant women often suffer from back strain late in their
pregnancy.
:::
:::

::: {#fs-id1165298545438 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1165298545440 data-type="problem"}
An old carpenter\'s trick to keep nails from bending when they are
pounded into hard materials is to grip the center of the nail firmly
with pliers. Why does this help?
:::
:::

::: {#fs-id1165298771893 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1165298771894 data-type="problem"}
When a glass bottle full of vinegar warms up, both the vinegar and the
glass expand, but vinegar expands significantly more with temperature
than glass. The bottle will break if it was filled to its tightly capped
lid. Explain why, and also explain how a pocket of air above the vinegar
would prevent the break. (This is the function of the air above liquids
in glass containers.)
:::
:::
:::

::: {#fs-id1165298820012 .problems-exercises depth="1" element-type="problems-exercises"}
### Problems & Exercises { data-type="title"}

::: {#fs-id1165298795593 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298795594 data-type="problem"}
During a circus act, one performer swings upside down hanging from a
trapeze holding another, also upside-down, performer by the legs. If the
upward force on the lower performer is three times her weight, how much
do the bones (the femurs) in her upper legs stretch? You may assume each
is equivalent to a uniform rod 35.0 cm long and 1.80 cm in radius. Her
mass is 60.0 kg.
:::

::: {#fs-id1165298841662 data-type="solution"}
::: {#eip-id1565399 data-type="equation"}
$${1\text{.}{\text{90} \times \text{10}^{- 3}}\ \text{cm}}{}$$
:::
:::
:::

::: {#fs-id1165298595705 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298595706 data-type="problem"}
During a wrestling match, a 150 kg wrestler briefly stands on one hand
during a maneuver designed to perplex his already moribund adversary. By
how much does the upper arm bone shorten in length? The bone can be
represented by a uniform rod 38.0 cm in length and 2.10 cm in radius.
:::
:::

::: {#fs-id1165298778825 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298778826 data-type="problem"}
\(a\) The "lead" in pencils is a graphite composition with a Young\'s
modulus of about ${1{\times \text{10}^{9}}\ {\text{N}/\text{m}^{2}}}{}$
. Calculate the change in length of the lead in an automatic pencil if
you tap it straight into the pencil with a force of 4.0 N. The lead is
0.50 mm in diameter and 60 mm long. (b) Is the answer reasonable? That
is, does it seem to be consistent with what you have observed when using
pencils?
:::

::: {#fs-id1165296220516 data-type="solution"}
(a)1 mm [\
]{data-type="newline"}(b) This does seem reasonable, since the lead does
seem to shrink a little when you push on it.
:::
:::

::: {#fs-id1165298941254 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298941255 data-type="problem"}
TV broadcast antennas are the tallest artificial structures on Earth. In
1987, a 72.0-kg physicist placed himself and 400 kg of equipment at the
top of one 610-m high antenna to perform gravity experiments. By how
much was the antenna compressed, if we consider it to be equivalent to a
steel cylinder 0.150 m in radius?
:::
:::

::: {#fs-id1165298598606 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298598607 data-type="problem"}
\(a\) By how much does a 65.0-kg mountain climber stretch her 0.800-cm
diameter nylon rope when she hangs 35.0 m below a rock outcropping? (b)
Does the answer seem to be consistent with what you have observed for
nylon ropes? Would it make sense if the rope were actually a bungee
cord?
:::

::: {#fs-id1165298944074 data-type="solution"}
(a)9 cm [\
]{data-type="newline"} (b)This seems reasonable for nylon climbing rope,
since it is not supposed to stretch that much.
:::
:::

::: {#fs-id1165298937277 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298937278 data-type="problem"}
A 20.0-m tall hollow aluminum flagpole is equivalent in strength to a
solid cylinder 4.00 cm in diameter. A strong wind bends the pole much as
a horizontal force of 900 N exerted at the top would. How far to the
side does the top of the pole flex?
:::
:::

::: {#fs-id1165296239036 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165296239037 data-type="problem"}
As an oil well is drilled, each new section of drill pipe supports its
own weight and that of the pipe and drill bit beneath it. Calculate the
stretch in a new 6.00 m length of steel pipe that supports 3.00 km of
pipe having a mass of 20.0 kg/m and a 100-kg drill bit. The pipe is
equivalent in strength to a solid cylinder 5.00 cm in diameter.
:::

::: {#fs-id1165298608719 data-type="solution"}
8.59 mm
:::
:::

::: {#fs-id1165298786214 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298786215 data-type="problem"}
Calculate the force a piano tuner applies to stretch a steel piano wire
8.00 mm, if the wire is originally 0.850 mm in diameter and 1.35 m long.
:::
:::

::: {#fs-id1165298982360 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298982361 data-type="problem"}
A vertebra is subjected to a shearing force of 500 N. Find the shear
deformation, taking the vertebra to be a cylinder 3.00 cm high and 4.00
cm in diameter.
:::

::: {#fs-id1165298858039 data-type="solution"}
::: {#eip-id1373472 data-type="equation"}
$${1\text{.}{\text{49} \times \text{10}^{- 7}}\ \text{m}}{}$$
:::
:::
:::

::: {#fs-id1165298797862 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298797863 data-type="problem"}
A disk between vertebrae in the spine is subjected to a shearing force
of 600 N. Find its shear deformation, taking it to have the shear
modulus of ${1{\times \text{10}^{9}}{\ \text{N}/\text{m}^{2}}}{}$ . The
disk is equivalent to a solid cylinder 0.700 cm high and 4.00 cm in
diameter.
:::
:::

::: {#fs-id1165296255735 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165296255736 data-type="problem"}
When using a pencil eraser, you exert a vertical force of 6.00 N at a
distance of 2.00 cm from the hardwood-eraser joint. The pencil is 6.00
mm in diameter and is held at an angle of $\text{20.0º}$ to the
horizontal. (a) By how much does the wood flex perpendicular to its
length? (b) How much is it compressed lengthwise?
:::

::: {#fs-id1165298654339 data-type="solution"}
\(a\) ${3\text{.}{\text{99} \times \text{10}^{- 7}}\ m}{}$

\(b\) ${9\text{.}{\text{67} \times \text{10}^{- 8}}\ m}{}$
:::
:::

::: {#fs-id1165298783085 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298783086 data-type="problem"}
To consider the effect of wires hung on poles, we take data from
[link](/m54876#fs-id1348788){.autogenerated-content}, in which tensions
in wires supporting a traffic light were calculated. The left wire made
an angle $\text{30.0º}$ below the horizontal with the top of its pole
and carried a tension of 108 N. The 12.0 m tall hollow aluminum pole is
equivalent in strength to a 4.50 cm diameter solid cylinder. (a) How far
is it bent to the side? (b) By how much is it compressed?
:::
:::

::: {#fs-id1165298713046 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298713047 data-type="problem"}
A farmer making grape juice fills a glass bottle to the brim and caps it
tightly. The juice expands more than the glass when it warms up, in such
a way that the volume increases by 0.2% (that is,
${{\Delta V/V_{0}} = {2 \times \text{10}^{- 3}}}{}$) relative to the
space available. Calculate the magnitude of the normal force exerted by
the juice per square centimeter if its bulk modulus is
${1\text{.}{8 \times \text{10}^{9}}\ \text{N/m}^{2}}{}$, assuming the
bottle does not break. In view of your answer, do you think the bottle
will survive?
:::

::: {#fs-id1165298481228 data-type="solution"}
${{4 \times \text{10}^{6}}\ \text{N/m}^{2}}{}$. This is about 36 atm,
greater than a typical jar can withstand.
:::
:::

::: {#fs-id1165298913397 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298913398 data-type="problem"}
\(a\) When water freezes, its volume increases by 9.05% (that is,
${{\Delta V/V_{0}} = 9}\text{.}{\text{05} \times \text{10}^{- 2}}$ ).
What force per unit area is water capable of exerting on a container
when it freezes? (It is acceptable to use the bulk modulus of water in
this problem.) (b) Is it surprising that such forces can fracture engine
blocks, boulders, and the like?
:::
:::

::: {#fs-id1165298740744 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298520715 data-type="problem"}
This problem returns to the tightrope walker studied in
[link](/m54857#fs-id986136){.autogenerated-content}, who created a
tension of ${3\text{.}{\text{94} \times \text{10}^{3}}\ N}{}$ in a wire
making an angle $\text{5.0º}$ below the horizontal with each supporting
pole. Calculate how much this tension stretches the steel wire if it was
originally 15 m long and 0.50 cm in diameter.
:::

::: {#fs-id1165298866753 data-type="solution"}
1.4 cm
:::
:::

::: {#fs-id1165296233210 data-type="exercise" element-type="problem-exercises"}
::: {#fs-id1165298620362 data-type="problem"}
The pole in [link](#import-auto-id1165296309614){.autogenerated-content}
is at a $\text{90.0º}$ bend in a power line and is therefore subjected
to more shear force than poles in straight parts of the line. The
tension in each line is
${4\text{.}{\text{00} \times \text{10}^{4}}\ N}{}$, at the angles shown.
The pole is 15.0 m tall, has an 18.0 cm diameter, and can be considered
to have half the strength of hardwood. (a) Calculate the compression of
the pole. (b) Find how much it bends and in what direction. (c) Find the
tension in a guy wire used to keep the pole straight if it is attached
to the top of the pole at an angle of $\text{30.0º}$ with the vertical.
(Clearly, the guy wire must be in the opposite direction of the bend.)

![This telephone pole is at a ${\text{90}\text{º}}{}$ bend in a power
line. A guy wire is attached to the top of the pole at an angle of
${\text{30}\text{º}}{}$ with the
vertical.](images/Figure_06_03_10a.jpg){#import-auto-id1165296309614}
:::
:::
:::

::: {data-type="glossary"}
### Glossary { data-type="glossary-title"}

deformation
:   change in shape due to the application of force

```{=html}
<!-- -->
```

Hooke\'s law
:   proportional relationship between the force $F{}$ on a material and
    the deformation ${\Delta L}{}$ it causes, ${F = k\Delta L}{}$

```{=html}
<!-- -->
```

tensile strength
:   measure of deformation for a given tension or compression

```{=html}
<!-- -->
```

stress
:   ratio of force to area

```{=html}
<!-- -->
```

strain
:   ratio of change in length to original length

```{=html}
<!-- -->
```

shear deformation
:   deformation perpendicular to the original length of an object
:::