Newton\'s First Law of Motion: Inertia
--------------------------------------

::: {#fs-id2242465 .learning-objectives depth="1"}
### Learning Objectives { data-type="title"}

By the end of this section, you will be able to:

-   Define mass and inertia.
-   Understand Newton\'s first law of motion.
:::

Experience suggests that an object at rest will remain at rest if left
alone, and that an object in motion tends to slow down and stop unless
some effort is made to keep it moving. What [Newton's first law of
motion]{#import-auto-id1777407
data-type="term"}**`<!-- no-selfclose -->`{=html}** states, however, is
the following:

::: {#fs-id2690663 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Newton's First Law of Motion
:::

There exists an inertial frame of reference such that a body at rest
remains at rest, or, if in motion, remains in motion at a constant
velocity unless acted on by a net external force.
:::

Note the repeated use of the verb "remains." We can think of this law as
preserving the status quo of motion.

The first law of motion postulates the existence of at least one frame
of reference which we call an inertial reference frame, relative to
which the motion of an object not subject to forces is a straight line
at a constant speed. An inertial reference frame is any reference frame
that is not itself accelerating. A car traveling at constant velocity is
an inertial reference frame. A car slowing down for a stoplight, or
speeding up after the light turns green, will be accelerating and is not
an inertial reference frame. Finally, when the car goes around a turn,
which is due to an acceleration changing the direction of the velocity
vector, it is not an inertial reference frame. Note that Newton's laws
of motion are only valid for inertial reference frames.

Rather than contradicting our experience, [Newton's first law of
motion]{data-type="term"} states that there must be a *cause* (which is
a net external force) *for there to be any change in velocity (either a
change in magnitude or direction)* in an inertial reference frame. We
will define *net external force* in the next section. An object sliding
across a table or floor slows down due to the net force of friction
acting on the object. If friction disappeared, would the object still
slow down?

The idea of cause and effect is crucial in accurately describing what
happens in various situations. For example, consider what happens to an
object sliding along a rough horizontal surface. The object quickly
grinds to a halt. If we spray the surface with talcum powder to make the
surface smoother, the object slides farther. If we make the surface even
smoother by rubbing lubricating oil on it, the object slides farther
yet. Extrapolating to a frictionless surface, we can imagine the object
sliding in a straight line indefinitely. Friction is thus the *cause*
*`<!-- no-selfclose -->`{=html}*of the slowing (consistent with Newton's
first law). The object would not slow down at all if friction were
completely eliminated. Consider an air hockey table. When the air is
turned off, the puck slides only a short distance before friction slows
it to a stop. However, when the air is turned on, it creates a nearly
frictionless surface, and the puck glides long distances without slowing
down. Additionally, if we know enough about the friction, we can
accurately predict how quickly the object will slow down. Friction is an
external force.

Newton's first law is completely general and can be applied to anything
from an object sliding on a table to a satellite in orbit to blood
pumped from the heart. Experiments have thoroughly verified that any
change in velocity (speed or direction) must be caused by an external
force. The idea of *generally applicable or universal laws* is important
not only here---it is a basic feature of all laws of physics.
Identifying these laws is like recognizing patterns in nature from which
further patterns can be discovered. The genius of Galileo, who first
developed the idea for the first law, and Newton, who clarified it, was
to ask the fundamental question, "What is the cause?" Thinking in terms
of cause and effect is a worldview fundamentally different from the
typical ancient Greek approach when questions such as "Why does a tiger
have stripes?" would have been answered in Aristotelian fashion, "That
is the nature of the beast." True perhaps, but not a useful insight.

::: {#fs-id1737594 depth="1"}
### Mass {#mass data-type="title"}

The property of a body to remain at rest or to remain in motion with
constant velocity is called [inertia]{#import-auto-id2134480
data-type="term"}. Newton's first law is often called the [law of
inertia]{#import-auto-id1408275 data-type="term"}. As we know from
experience, some objects have more inertia than others. It is obviously
more difficult to change the motion of a large boulder than that of a
basketball, for example. The inertia of an object is measured by its
[mass]{#import-auto-id1500464 data-type="term"}.

An object with a small mass will exhibit less inertia and be more
affected by other objects. An object with a large mass will exhibit
greater inertia and be less affected by other objects. This inertial
mass of an object is a measure of how difficult it is to alter the
uniform motion of the object by an external force.

Roughly speaking, mass is a measure of the amount of "stuff" (or matter)
in something. The quantity or amount of matter in an object is
determined by the numbers of atoms and molecules of various types it
contains. Unlike weight, mass does not vary with location. The mass of
an object is the same on Earth, in orbit, or on the surface of the Moon.
In practice, it is very difficult to count and identify all of the atoms
and molecules in an object, so masses are not often determined in this
manner. Operationally, the masses of objects are determined by
comparison with the standard kilogram.
:::

::: {#fs-id2448968 data-type="exercise" element-type="check-understanding" data-label=""}
::: {data-type="title"}
Check Your Understanding
:::

::: {#fs-id3175448 data-type="problem"}
Which has more mass: a kilogram of cotton balls or a kilogram of gold?
:::

::: {#fs-id3255910 data-type="solution"}
They are equal. A kilogram of one substance is equal in mass to a
kilogram of another substance. The quantities that might differ between
them are volume and density.
:::
:::

::: {#fs-id1651376-summary depth="1"}
### Section Summary { data-type="title"}

-   [Newton's first law of motion]{data-type="term"} states that in an
    inertial frame of reference a body at rest remains at rest, or, if
    in motion, remains in motion at a constant velocity unless acted on
    by a net external force. This is also known as the [law of
    inertia]{data-type="term"}.
-   [Inertia]{data-type="term"}**`<!-- no-selfclose -->`{=html}** is the
    tendency of an object to remain at rest or remain in motion. Inertia
    is related to an object's mass.
-   [Mass]{data-type="term"} is the quantity of matter in a substance.
:::

::: {#fs-id2668844 .conceptual-questions depth="1" element-type="conceptual-questions"}
### Conceptual Questions { data-type="title"}

::: {#fs-id1263177 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1248749 data-type="problem"}
How are inertia and mass related?
:::
:::

::: {#fs-id1561865 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id2674431 data-type="problem"}
What is the relationship between weight and mass? Which is an intrinsic,
unchanging property of a body?
:::
:::
:::

::: {data-type="glossary"}
### Glossary { data-type="glossary-title"}

inertia
:   the tendency of an object to remain at rest or remain in motion

```{=html}
<!-- -->
```

law of inertia
:   see Newton's first law of motion

```{=html}
<!-- -->
```

mass
:   the quantity of matter in a substance; measured in kilograms

```{=html}
<!-- -->
```

Newton's first law of motion
:   in an inertial frame of reference, a body at rest remains at rest,
    or, if in motion, remains in motion at a constant velocity unless
    acted on by a net external force; also known as the law of inertia
:::