Extended Topic: The Four Basic Forces---An Introduction
-------------------------------------------------------

::: {#fs-id1910513 .learning-objectives depth="1"}
### Learning Objectives { data-type="title"}

By the end of this section, you will be able to:

-   Understand the four basic forces that underlie the processes in
    nature.

The information presented in this section supports the following AP®
learning objectives and science practices:

-   **3.C.4.1** The student is able to make claims about various contact
    forces between objects based on the microscopic cause of those
    forces. **(S.P. 6.1)**
-   **3.C.4.2** The student is able to explain contact forces (tension,
    friction, normal, buoyant, spring) as arising from interatomic
    electric forces and that they therefore have certain directions.
    **(S.P. 6.2)**
-   **3.G.1.1** The student is able to articulate situations when the
    gravitational force is the dominant force and when the
    electromagnetic, weak, and strong forces can be ignored. **(S.P.
    7.1)**
:::

One of the most remarkable simplifications in physics is that only four
distinct forces account for all known phenomena. In fact, nearly all of
the forces we experience directly are due to only one basic force,
called the electromagnetic force. (The gravitational force is the only
force we experience directly that is not electromagnetic.) This is a
tremendous simplification of the myriad of *apparently* different forces
we can list, only a few of which were discussed in the previous section.
As we will see, the basic forces are all thought to act through the
exchange of microscopic carrier particles, and the characteristics of
the basic forces are determined by the types of particles exchanged.
Action at a distance, such as the gravitational force of Earth on the
Moon, is explained by the existence of a [force
field]{#import-auto-id2990636 data-type="term"} rather than by "physical
contact."

The *four basic forces* are the gravitational force, the electromagnetic
force, the weak nuclear force, and the strong nuclear force. Their
properties are summarized in
[link](#import-auto-id1588108){.autogenerated-content}. Since the weak
and strong nuclear forces act over an extremely short range, the size of
a nucleus or less, we do not experience them directly, although they are
crucial to the very structure of matter. These forces determine which
nuclei are stable and which decay, and they are the basis of the release
of energy in certain nuclear reactions. Nuclear forces determine not
only the stability of nuclei, but also the relative abundance of
elements in nature. The properties of the nucleus of an atom determine
the number of electrons it has and, thus, indirectly determine the
chemistry of the atom. More will be said of all of these topics in later
chapters.

::: {#fs-id3025368 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Concept Connections: The Four Basic Forces
:::

The four basic forces will be encountered in more detail as you progress
through the text. The gravitational force is defined in [Uniform
Circular Motion and Gravitation](/m54986), electric force in [Electric
Charge and Electric Field](/m55297), magnetic force in
[Magnetism](/m55372), and nuclear forces in [Radioactivity and Nuclear
Physics](/m54935). On a macroscopic scale, electromagnetism and gravity
are the basis for all forces. The nuclear forces are vital to the
substructure of matter, but they are not directly experienced on the
macroscopic scale.
:::

```{=html}
<table id="import-auto-id1588108" summary="A table listing the properties of four basic forces. The table has five columns indicating the type of force, its approximate relative strength, its range, whether it is attractive or repulsive, and the carrier particle(s).">
```
```{=html}
<caption>
```
::: {.tinysection}
[Properties of the Four Basic
Forces[\[footnote\]](#eip-id1997179)]{data-type="title"}
:::

```{=html}
<aside role="doc-footnote" type="footnote" id="eip-id1997179">
```
The graviton is a proposed particle, though it has not yet been observed
by scientists. See the discussion of gravitational waves later in this
section. The particles $\text{W}^{+}{}$, $\text{W}^{-}{}$, and
$\text{Z}^{0}{}$ are called vector bosons; these were predicted by
theory and first observed in 1983. There are eight types of gluons
proposed by scientists, and their existence is indicated by meson
exchange in the nuclei of atoms.

```{=html}
</aside>
```
```{=html}
</caption>
```
```{=html}
<thead>
```
```{=html}
<tr>
```
```{=html}
<th>
```
Force

```{=html}
</th>
```
```{=html}
<th>
```
Approximate Relative Strengths

```{=html}
</th>
```
```{=html}
<th>
```
Range

```{=html}
</th>
```
```{=html}
<th>
```
Attraction/Repulsion

```{=html}
</th>
```
```{=html}
<th>
```
Carrier Particle

```{=html}
</th>
```
```{=html}
</tr>
```
```{=html}
</thead>
```
```{=html}
<tbody>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Gravitational

```{=html}
</td>
```
```{=html}
<td>
```
$$\text{10}^{- \text{38}}{}$$

```{=html}
</td>
```
```{=html}
<td>
```
$$\infty{}$$

```{=html}
</td>
```
```{=html}
<td>
```
attractive only

```{=html}
</td>
```
```{=html}
<td>
```
Graviton

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Electromagnetic

```{=html}
</td>
```
```{=html}
<td>
```
$$\text{10}^{–2}{}$$

```{=html}
</td>
```
```{=html}
<td>
```
$$\infty{}$$

```{=html}
</td>
```
```{=html}
<td>
```
attractive and repulsive

```{=html}
</td>
```
```{=html}
<td>
```
Photon

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Weak nuclear

```{=html}
</td>
```
```{=html}
<td>
```
$$\text{10}^{–\text{13}}$$

```{=html}
</td>
```
```{=html}
<td>
```
\< $10^{–18}\text{m}$

```{=html}
</td>
```
```{=html}
<td>
```
attractive and repulsive

```{=html}
</td>
```
```{=html}
<td>
```
$\text{W}^{+}{}$, $\text{W}^{–}{}$, $\text{Z}^{0}{}$

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
<tr>
```
```{=html}
<td>
```
Strong nuclear

```{=html}
</td>
```
```{=html}
<td>
```
$$1$$

```{=html}
</td>
```
```{=html}
<td>
```
\< $10^{–15}\text{m}$

```{=html}
</td>
```
```{=html}
<td>
```
attractive and repulsive

```{=html}
</td>
```
```{=html}
<td>
```
gluons

```{=html}
</td>
```
```{=html}
</tr>
```
```{=html}
</tbody>
```
```{=html}
</table>
```
The gravitational force is surprisingly weak---it is only because
gravity is always attractive that we notice it at all. Our weight is the
gravitational force due to the *entire`<!-- no-selfclose -->`{=html}*
Earth acting on us. On the very large scale, as in astronomical systems,
the gravitational force is the dominant force determining the motions of
moons, planets, stars, and galaxies. The gravitational force also
affects the nature of space and time. As we shall see later in the study
of general relativity, space is curved in the vicinity of very massive
bodies, such as the Sun, and time actually slows down near massive
bodies.

Take a good look at the ranges for the four fundamental forces listed in
[link](#import-auto-id1588108){.autogenerated-content}. The range of the
strong nuclear force, 10^−15^ m, is approximately the size of the
nucleus of an atom; the weak nuclear force has an even shorter range. At
scales on the order of 10−10 m, approximately the size of an atom, both
nuclear forces are completely dominated by the electromagnetic force.
Notice that this scale is still utterly tiny compared to our everyday
experience. At scales that we do experience daily, electromagnetism
tends to be negligible, due to its attractive and repulsive properties
canceling each other out. That leaves gravity, which is usually the
strongest of the forces at scales above \~10^−4^ m, and hence includes
our everyday activities, such as throwing, climbing stairs, and walking.

Electromagnetic forces can be either attractive or repulsive. They are
long-range forces, which act over extremely large distances, and they
nearly cancel for macroscopic objects. (Remember that it is the *net*
external force that is important.) If they did not cancel,
electromagnetic forces would completely overwhelm the gravitational
force. The electromagnetic force is a combination of electrical forces
(such as those that cause static electricity) and magnetic forces (such
as those that affect a compass needle). These two forces were thought to
be quite distinct until early in the 19th century, when scientists began
to discover that they are different manifestations of the same force.
This discovery is a classical case of the *unification of forces*.
Similarly, friction, tension, and all of the other classes of forces we
experience directly (except gravity, of course) are due to
electromagnetic interactions of atoms and molecules. It is still
convenient to consider these forces separately in specific applications,
however, because of the ways they manifest themselves.

::: {#fs-id2423408 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Concept Connections: Unifying Forces
:::

Attempts to unify the four basic forces are discussed in relation to
elementary particles later in this text. By "unify" we mean finding
connections between the forces that show that they are different
manifestations of a single force. Even if such unification is achieved,
the forces will retain their separate characteristics on the macroscopic
scale and may be identical only under extreme conditions such as those
existing in the early universe.
:::

Physicists are now exploring whether the four basic forces are in some
way related. Attempts to unify all forces into one come under the rubric
of Grand Unified Theories (GUTs), with which there has been some success
in recent years. It is now known that under conditions of extremely high
density and temperature, such as existed in the early universe, the
electromagnetic and weak nuclear forces are indistinguishable. They can
now be considered to be different manifestations of one force, called
the *electroweak* force. So the list of four has been reduced in a sense
to only three. Further progress in unifying all forces is proving
difficult---especially the inclusion of the gravitational force, which
has the special characteristics of affecting the space and time in which
the other forces exist.

While the unification of forces will not affect how we discuss forces in
this text, it is fascinating that such underlying simplicity exists in
the face of the overt complexity of the universe. There is no reason
that nature must be simple---it simply is.

::: {#import-auto-id3077454 depth="1"}
### Action at a Distance: Concept of a Field {#action-at-a-distance-concept-of-a-field data-type="title"}

All forces act at a distance. This is obvious for the gravitational
force. Earth and the Moon, for example, interact without coming into
contact. It is also true for all other forces. Friction, for example, is
an electromagnetic force between atoms that may not actually touch. What
is it that carries forces between objects? One way to answer this
question is to imagine that a [force field]{#import-auto-id3093199
data-type="term"} surrounds whatever object creates the force. A second
object (often called a *test object*) placed in this field will
experience a force that is a function of location and other variables.
The field itself is the "thing" that carries the force from one object
to another. The field is defined so as to be a characteristic of the
object creating it; the field does not depend on the test object placed
in it. Earth's gravitational field, for example, is a function of the
mass of Earth and the distance from its center, independent of the
presence of other masses. The concept of a field is useful because
equations can be written for force fields surrounding objects (for
gravity, this yields ${w = \text{mg}}{}$ at Earth's surface), and
motions can be calculated from these equations. (See
[link](#import-auto-id1577565){.autogenerated-content}.)

![The electric force field between a positively charged particle and a
negatively charged particle. When a positive test charge is placed in
the field, the charge will experience a force in the direction of the
force field lines.](images/Figure_04_08_01.jpg){#import-auto-id1577565}

::: {#fs-id2639325 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Concept Connections: Force Fields
:::

The concept of a **force field** is also used in connection with
electric charge and is presented in [Electric Charge and Electric
Field](/m55297). It is also a useful idea for all the basic forces, as
will be seen in [Particle Physics](/m54854). Fields help us to visualize
forces and how they are transmitted, as well as to describe them with
precision and to link forces with subatomic carrier particles.
:::

::: {#fs-id1421634 .note data-type="note"}
::: {#fs-id1399053 data-type="title"}
Making Connections: Vector and Scalar Fields
:::

These fields may be either scalar or vector fields. Gravity and
electromagnetism are examples of vector fields. A test object placed in
such a field will have both the magnitude and direction of the resulting
force on the test object completely defined by the object's location in
the field. We will later cover examples of scalar fields, which have a
magnitude but no direction.
:::

The field concept has been applied very successfully; we can calculate
motions and describe nature to high precision using field equations. As
useful as the field concept is, however, it leaves unanswered the
question of what carries the force. It has been proposed in recent
decades, starting in 1935 with Hideki Yukawa's (1907--1981) work on the
strong nuclear force, that all forces are transmitted by the exchange of
elementary particles. We can visualize particle exchange as analogous to
macroscopic phenomena such as two people passing a basketball back and
forth, thereby exerting a repulsive force without touching one another.
(See [link](#import-auto-id2011579){.autogenerated-content}.)

![The exchange of masses resulting in repulsive forces. (a) The person
throwing the basketball exerts a force
$\textbf{F}_{\text{p1}}{}$~`<!-- no-selfclose -->`{=html}~ on it toward
the other person and feels a reaction force $\textbf{F}_{\text{B}}$ away
from the second person. (b) The person catching the basketball exerts a
force $\textbf{F}_{\text{p2}}$ on it to stop the ball and feels a
reaction force $\textbf{F'}_{\text{B}}{}$ away from the first person.
(c) The analogous exchange of a meson between a proton and a neutron
carries the strong nuclear forces $\textbf{F}_{\text{exch}}$ and
$\textbf{F'}_{\text{exch}}$ between them. An attractive force can also
be exerted by the exchange of a mass---if person 2 pulled the basketball
away from the first person as he tried to retain it, then the force
between them would be
attractive.](images/Figure_04_08_02.jpg){#import-auto-id2011579}

This idea of particle exchange deepens rather than contradicts field
concepts. It is more satisfying philosophically to think of something
physical actually moving between objects acting at a distance.
[link](#import-auto-id1588108){.autogenerated-content} lists the
exchange or [carrier particles]{#import-auto-id1561662
data-type="term"}, both observed and proposed, that carry the four
forces. But the real fruit of the particle-exchange proposal is that
searches for Yukawa's proposed particle found it *and* a number of
others that were completely unexpected, stimulating yet more research.
All of this research eventually led to the proposal of quarks as the
underlying substructure of matter, which is a basic tenet of GUTs. If
successful, these theories will explain not only forces, but also the
structure of matter itself. Yet physics is an experimental science, so
the test of these theories must lie in the domain of the real world. As
of this writing, scientists at the CERN laboratory in Switzerland are
starting to test these theories using the world's largest particle
accelerator: the Large Hadron Collider. This accelerator (27 km in
circumference) allows two high-energy proton beams, traveling in
opposite directions, to collide. An energy of 14 trillion electron volts
will be available. It is anticipated that some new particles, possibly
force carrier particles, will be found. (See
[link](#import-auto-id2658974){.autogenerated-content}.) One of the
force carriers of high interest that researchers hope to detect is the
Higgs boson. The observation of its properties might tell us why
different particles have different masses.

![The world's largest particle accelerator spans the border between
Switzerland and France. Two beams, traveling in opposite directions
close to the speed of light, collide in a tube similar to the central
tube shown here. External magnets determine the beam's path. Special
detectors will analyze particles created in these collisions. Questions
as broad as what is the origin of mass and what was matter like the
first few seconds of our universe will be explored. This accelerator
began preliminary operation in 2008. (credit: Frank
Hommes)](images/Figure_04_08_03.jpg){#import-auto-id2658974}

Tiny particles also have wave-like behavior, something we will explore
more in a later chapter. To better understand force-carrier particles
from another perspective, let us consider gravity. The search for
gravitational waves has been going on for a number of years. Almost 100
years ago, Einstein predicted the existence of these waves as part of
his general theory of relativity. Gravitational waves are created during
the collision of massive stars, in black holes, or in supernova
explosions---like shock waves. These gravitational waves will travel
through space from such sites much like a pebble dropped into a pond
sends out ripples---except these waves move at the speed of light. A
detector apparatus has been built in the U.S., consisting of two large
installations nearly 3000 km apart---one in Washington state and one in
Louisiana! The facility is called the Laser Interferometer
Gravitational-Wave Observatory (LIGO). Each installation is designed to
use optical lasers to examine any slight shift in the relative positions
of two masses due to the effect of gravity waves. The two sites allow
simultaneous measurements of these small effects to be separated from
other natural phenomena, such as earthquakes. Initial operation of the
detectors began in 2002, and work is proceeding on increasing their
sensitivity. Similar installations have been built in Italy (VIRGO),
Germany (GEO600), and Japan (TAMA300) to provide a worldwide network of
gravitational wave detectors.

International collaboration in this area is moving into space with the
joint EU/US project LISA (Laser Interferometer Space Antenna).
Earthquakes and other Earthly noises will be no problem for these
monitoring spacecraft. LISA will complement LIGO by looking at much more
massive black holes through the observation of gravitational-wave
sources emitting much larger wavelengths. Three satellites will be
placed in space above Earth in an equilateral triangle (with
5,000,000-km sides)
([link](#import-auto-id3032532){.autogenerated-content}). The system
will measure the relative positions of each satellite to detect passing
gravitational waves. Accuracy to within 10% of the size of an atom will
be needed to detect any waves. The launch of this project might be as
early as 2018.

*"I'm sure LIGO will tell us something about the universe that we didn't
know before. The history of science tells us that any time you go where
you haven't been before, you usually find something that really shakes
the scientific paradigms of the day. Whether gravitational wave
astrophysics will do that, only time will tell."* ---David Reitze, LIGO
Input Optics Manager, University of Florida

![Space-based future experiments for the measurement of gravitational
waves. Shown here is a drawing of LISA's orbit. Each satellite of LISA
will consist of a laser source and a mass. The lasers will transmit a
signal to measure the distance between each satellite's test mass. The
relative motion of these masses will provide information about passing
gravitational waves. (credit:
NASA)](images/Figure_04_08_04.jpg){#import-auto-id3032532}

The ideas presented in this section are but a glimpse into topics of
modern physics that will be covered in much greater depth in later
chapters.
:::

::: {#fs-id1546076 .ap-test-prep depth="1" element-type="ap-test-prep"}
### Test Prep for AP Courses { data-type="title"}

::: {#fs-id1342174 data-type="exercise" element-type="ap-test-prep"}
::: {#fs-id895568 data-type="problem"}
Which phenomenon correctly describes the direction and magnitude of
normal forces?

a.  electromagnetic attraction
b.  electromagnetic repulsion
c.  gravitational attraction
d.  gravitational repulsion
:::

::: {#fs-id2173841 data-type="solution"}
\(b\)
:::
:::

::: {#fs-id1835056 data-type="exercise" element-type="ap-test-prep"}
::: {#fs-id1356337 data-type="problem"}
Explain which of the four fundamental forces is responsible for a ball
bouncing off the ground after it hits, and why this force has this
effect.
:::

`<!--<solution id="fs-id1797582">
<para id="fs-id1327682">This outcome is due to electromagnetic repulsion between the electrons in atoms. The electrons in the ball repel those in the ground, and vice versa.</para>
</solution>-->`{=html}
:::

::: {#fs-id1447352 data-type="exercise" element-type="ap-test-prep"}
::: {#fs-id1434025 data-type="problem"}
Which of the basic forces best explains tension in a rope being pulled
between two people? Is the acting force causing attraction or repulsion
in this instance?

a.  gravity; attraction
b.  electromagnetic; attraction
c.  weak and strong nuclear; attraction
d.  weak and strong nuclear; repulsion
:::

::: {#fs-id1347751 data-type="solution"}
\(b\)
:::
:::

::: {#fs-id1679830 data-type="exercise" element-type="ap-test-prep"}
::: {#fs-id1205612 data-type="problem"}
Explain how interatomic electric forces produce the normal force, and
why it has the direction it does.
:::

`<!--<solution id="fs-id1312453">
<para id="fs-id1798574">The outer layers of electrons in the atoms of both an object and the surface with which it is in contact mutually repel each other. Furthermore, while any individual pair of electrons might have a vector that is not perpendicular to the surface, the net sum of all the many, many interactions is perpendicular to the surface.</para>
</solution>-->`{=html}
:::

::: {#fs-id1656257 data-type="exercise" element-type="ap-test-prep"}
::: {#fs-id1472000 data-type="problem"}
The gravitational force is the weakest of the four basic forces. In
which case can the electromagnetic, strong, and weak forces be ignored
because the gravitational force is so strongly dominant?

a.  a person jumping on a trampoline
b.  a rocket blasting off from Earth
c.  a log rolling down a hill
d.  all of the above
:::

::: {#fs-id2166894 data-type="solution"}
\(d\)
:::
:::

::: {#fs-id1338709 data-type="exercise" element-type="ap-test-prep"}
::: {#fs-id1374823 data-type="problem"}
Describe a situation in which gravitational force is the dominant force.
Why can the other three basic forces be ignored in the situation you
described?
:::

`<!--<solution id="fs-id1623442">
<para id="fs-id895313">When a ball is thrown, gravity is the only one of the four fundamental forces necessary to describe the trajectory. The distances involved are far too large for either of the nuclear forces, and the net electric charge on the ball is zero or so close to it that electromagnetism has no effect.</para>
</solution>-->`{=html}
:::
:::

::: {#fs-id1993313-summary depth="1"}
### Summary { data-type="title"}

-   [The various types of forces that are categorized for use in many
    applications are all manifestations of the *four basic forces* in
    nature.]{#import-auto-id2055006}
-   [The properties of these forces are summarized in
    [link](#import-auto-id1588108){.autogenerated-content}.]{#import-auto-id1355832}
-   [Everything we experience directly without sensitive instruments is
    due to either electromagnetic forces or gravitational forces. The
    nuclear forces are responsible for the submicroscopic structure of
    matter, but they are not directly sensed because of their short
    ranges. Attempts are being made to show all four forces are
    different manifestations of a single unified
    force.]{#import-auto-id1381444}
-   [A force field surrounds an object creating a force and is the
    carrier of that force.]{#import-auto-id3191620}
:::

::: {#fs-id3199417 .conceptual-questions depth="1" element-type="conceptual-questions"}
### Conceptual Questions { data-type="title"}

::: {#fs-id1397916 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id2602098 data-type="problem"}
Explain, in terms of the properties of the four basic forces, why people
notice the gravitational force acting on their bodies if it is such a
comparatively weak force.
:::
:::

::: {#fs-id1402987 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id3358931 data-type="problem"}
What is the dominant force between astronomical objects? Why are the
other three basic forces less significant over these very large
distances?
:::
:::

::: {#fs-id1038237 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1038256 data-type="problem"}
Give a detailed example of how the exchange of a particle can result in
an **attractive** force. (For example, consider one child pulling a toy
out of the hands of another.)
:::
:::
:::

::: {#fs-id3082682 .problems-exercises depth="1" element-type="problems-exercises"}
### Problem Exercises { data-type="title"}

::: {#fs-id2680982 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1413270 data-type="problem"}
\(a\) What is the strength of the weak nuclear force relative to the
strong nuclear force? (b) What is the strength of the weak nuclear force
relative to the electromagnetic force? Since the weak nuclear force acts
at only very short distances, such as inside nuclei, where the strong
and electromagnetic forces also act, it might seem surprising that we
have any knowledge of it at all. We have such knowledge because the weak
nuclear force is responsible for beta decay, a type of nuclear decay not
explained by other forces.
:::

::: {#fs-id2688655 data-type="solution"}
\(a\) ${1 \times \text{10}^{- \text{13}}}{}$

\(b\) ${1 \times \text{10}^{- \text{11}}}{}$
:::
:::

::: {#fs-id2670330 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1935090 data-type="problem"}
\(a\) What is the ratio of the strength of the gravitational force to
that of the strong nuclear force? (b) What is the ratio of the strength
of the gravitational force to that of the weak nuclear force? (c) What
is the ratio of the strength of the gravitational force to that of the
electromagnetic force? What do your answers imply about the influence of
the gravitational force on atomic nuclei?
:::
:::

::: {#fs-id3092040 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id3092946 data-type="problem"}
What is the ratio of the strength of the strong nuclear force to that of
the electromagnetic force? Based on this ratio, you might expect that
the strong force dominates the nucleus, which is true for small nuclei.
Large nuclei, however, have sizes greater than the range of the strong
nuclear force. At these sizes, the electromagnetic force begins to
affect nuclear stability. These facts will be used to explain nuclear
fusion and fission later in this text.
:::

::: {#fs-id2408217 data-type="solution"}
$\text{10}^{2}{}$
:::
:::
:::

::: {data-type="glossary"}
### Glossary { data-type="glossary-title"}

carrier particle
:   a fundamental particle of nature that is surrounded by a
    characteristic force field; photons are carrier particles of the
    electromagnetic force

```{=html}
<!-- -->
```

force field
:   a region in which a test particle will experience a force
:::