Projectile Motion
-----------------

::: {#fs-id1563341 .learning-objectives depth="1"}
### Learning Objectives { data-type="title"}

By the end of this section, you will be able to:

-   Identify and explain the properties of a projectile, such as
    acceleration due to gravity, range, maximum height, and trajectory.
-   Determine the location and velocity of a projectile at different
    points in its trajectory.
-   Apply the principle of independence of motion to solve projectile
    motion problems.

The information presented in this section supports the following AP®
learning objectives:

-   **3.A.1.1** The student is able to express the motion of an object
    using narrative, mathematical, and graphical representations.
    **(S.P. 1.5, 2.1, 2.2)**
-   **3.A.1.3** The student is able to analyze experimental data
    describing the motion of an object and is able to express the
    results of the analysis using narrative, mathematical, and graphical
    representations. **(S.P. 5.1)**
:::

[Projectile motion]{#import-auto-id1560216 data-type="term"} is the
[motion]{#import-auto-id1846113 data-type="term"} of an object thrown or
projected into the air, subject to only the acceleration of gravity. The
object is called a [projectile]{#import-auto-id1809247
data-type="term"}, and its path is called its
[trajectory]{#import-auto-id1397020 data-type="term"}. The motion of
falling objects, as covered in [Problem-Solving Basics for
One-Dimensional Kinematics](/m54774), is a simple one-dimensional type
of projectile motion in which there is no horizontal movement. In this
section, we consider two-dimensional projectile motion, such as that of
a football or other object for which [air
resistance]{#import-auto-id1230666 data-type="term"} **is negligible**.

The most important fact to remember here is that **motions along
perpendicular axes are independent** and thus can be analyzed
separately. This fact was discussed in [Kinematics in Two Dimensions: An
Introduction](/m54779), where vertical and horizontal motions were seen
to be independent. The key to analyzing two-dimensional projectile
motion is to break it into two motions, one along the horizontal axis
and the other along the vertical. (This choice of axes is the most
sensible, because acceleration due to gravity is vertical---thus, there
will be no acceleration along the horizontal axis when air resistance is
negligible.) As is customary, we call the horizontal axis the **x**-axis
and the vertical axis the **y**-axis.
[link](#import-auto-id2242290){.autogenerated-content} illustrates the
notation for displacement, where $\mathbf{s}{}$ is defined to be the
total displacement and $\mathbf{x}{}$ and $\mathbf{y}{}$ are its
components along the horizontal and vertical axes, respectively. The
magnitudes of these vectors are **s**, **x**, and **y**. (Note that in
the last section we used the notation $\mathbf{A}{}$ to represent a
vector with components $\mathbf{A}_{x}{}$ and $\mathbf{A}_{y}{}$. If we
continued this format, we would call displacement $\mathbf{s}{}$ with
components $\mathbf{s}_{x}{}$ and $\mathbf{s}_{y}{}$. However, to
simplify the notation, we will simply represent the component vectors as
$\mathbf{x}{}$ and $\mathbf{y}{}$.)

Of course, to describe motion we must deal with velocity and
acceleration, as well as with displacement. We must find their
components along the **x**- and **y**-axes, too. We will assume all
forces except gravity (such as air resistance and friction, for example)
are negligible. The components of acceleration are then very simple:
${{a_{y} = –g} = –9.80\ m\text{/s}^{2}}{}$. (Note that this definition
assumes that the upwards direction is defined as the positive direction.
If you arrange the coordinate system instead such that the downwards
direction is positive, then acceleration due to gravity takes a positive
value.) Because gravity is vertical, ${a_{x} = 0}{}$. Both accelerations
are constant, so the kinematic equations can be used.

::: {#fs-id1767845 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Review of Kinematic Equations (constant $a$)
:::

::: {#eip-891 data-type="equation"}
$${{x =}x_{0}{+}\overset{-}{v}t}{}$$
:::

::: {#eip-557 data-type="equation"}
$${{\overset{-}{v} =}\frac{v_{0} + v}{2}}{}$$
:::

::: {#eip-405 data-type="equation"}
$${v = {v_{0} + \text{at}}}{}$$
:::

::: {#eip-556 data-type="equation"}
$${{x = {x_{0} + v_{0}}}{t + \frac{1}{2}}\text{at}^{2}}{}$$
:::

::: {#eip-389 data-type="equation"}
$${{v^{2} = {v_{0}^{2} + 2a}}({x - x_{0}})}\text{.}{}$$
:::
:::

![The total displacement $\mathbf{s}{}$ of a soccer ball at a point
along its path. The vector $\mathbf{s}{}$ has components $\mathbf{x}{}$
and $\mathbf{y}{}$ along the horizontal and vertical axes. Its magnitude
is $s{}$, and it makes an angle $\theta{}$ with the
horizontal.](images/Figure_03_04_01.jpg){#import-auto-id2242290}

Given these assumptions, the following steps are then used to analyze
projectile motion:

***Step 1.*** *Resolve or break the motion into horizontal and vertical
components along the x- and y-axes.* These axes are perpendicular, so
${{A_{x} = A}\ \text{cos}\ \theta}{}$ and
${{A_{y} = A}\ \text{sin}\ \theta}{}$ are used. The magnitude of the
components of displacement $\mathbf{s}{}$ along these axes are $x{}$ and
${y.}{}$ The magnitudes of the components of the velocity $\mathbf{v}{}$
are ${{v_{x} = v}\ \text{cos}\ \theta}{}$ and
${{v_{y} = v}\ \text{sin}\ {\theta,}}{}$ where $v{}$ is the magnitude of
the velocity and $\theta{}$ is its direction, as shown in
[link](#import-auto-id1815222){.autogenerated-content}. Initial values
are denoted with a subscript 0, as usual.

***Step 2.*** *Treat the motion as two independent one-dimensional
motions, one horizontal and the other vertical.* The kinematic equations
for horizontal and vertical motion take the following forms:

::: {#eip-338 data-type="equation"}
$${\text{Horizontal\ Motion}({a_{x} = 0})}{}$$
:::

::: {#eip-362 data-type="equation"}
$${{x = {x_{0} + v_{x}}}t}{}$$
:::

::: {#eip-627 data-type="equation"}
$${{{v_{x} = v_{0x}} = v_{x}} = \text{velocity\ is\ a\ constant.}}{}$$
:::

::: {#eip-293 data-type="equation"}
$${\text{Vertical\ Motion}\operatorname{}(\text{assuming\ positive\ is\ up}\ \operatorname{}{{a_{y} = {- g}} = {{- 9.}\text{80}}}\operatorname{}\text{m/s}^{2})}{}$$
:::

::: {#eip-131 data-type="equation"}
$${{y = {y_{0} + \frac{1}{2}}}({v_{0y} + v_{y}})t}{}$$
:::

::: {#eip-305 data-type="equation"}
$${v_{y} = {v_{0y} - \text{gt}}}{}$$
:::

::: {#eip-542 data-type="equation"}
$${{y = {y_{0} + v_{0y}}}{t - \frac{1}{2}}{gt}^{2}}{}$$
:::

::: {#eip-243 data-type="equation"}
$${{v_{y}^{2} = {v_{0y}^{2} - 2g}}({y - y_{0}})\text{.}}{}$$
:::

***Step 3.*** *Solve for the unknowns in the two separate motions---one
horizontal and one vertical.* Note that the only common variable between
the motions is time $t{}$. The problem solving procedures here are the
same as for one-dimensional [kinematics]{data-type="term"} and are
illustrated in the solved examples below.

***Step 4.*** *Recombine the two motions to find the total displacement*
$\textbf{s}$ *and velocity* $\textbf{v}{}$. Because the *x* - and *y*
-motions are perpendicular, we determine these vectors by using the
techniques outlined in the [Vector Addition and Subtraction: Analytical
Methods](/m54783) and employing ${A = \sqrt{A_{x}^{2} + A_{y}^{2}}}{}$
and ${{\theta = \text{tan}^{- 1}}({A_{y}/A_{x}})}{}$ in the following
form, where $\theta{}$ is the direction of the displacement
$\mathbf{s}{}$ and $\theta_{v}{}$ is the direction of the velocity
$\mathbf{v}{}$:

::: {.tinysection}
[Total displacement and velocity]{data-type="title"}
:::

::: {#eip-743 data-type="equation"}
$${s = \sqrt{x^{2} + y^{2}}}{}$$
:::

::: {#eip-373 data-type="equation"}
$${{\theta = \text{tan}^{- 1}}({y/x})}{}$$
:::

::: {#eip-679 data-type="equation"}
$${v = \sqrt{v_{x}^{2} + v_{y}^{2}}}{}$$
:::

::: {#eip-264 data-type="equation"}
$${{\theta_{v} = \text{tan}^{- 1}}({v_{y}/v_{x}})\text{.}}{}$$
:::

![(a) We analyze two-dimensional projectile motion by breaking it into
two independent one-dimensional motions along the vertical and
horizontal axes. (b) The horizontal motion is simple, because
${a_{x} = 0}{}$ and $v_{x}{}$ is thus constant. (c) The velocity in the
vertical direction begins to decrease as the object rises; at its
highest point, the vertical velocity is zero. As the object falls
towards the Earth again, the vertical velocity increases again in
magnitude but points in the opposite direction to the initial vertical
velocity. (d) The *x* - and *y* -motions are recombined to give the
total velocity at any given point on the
trajectory.](images/Figure_03_04_02.jpg){#import-auto-id1815222}

::: {#fs-id2175010 data-type="example"}
::: {data-type="title"}
A Fireworks Projectile Explodes High and Away
:::

During a fireworks display, a shell is shot into the air with an initial
speed of 70.0 m/s at an angle of $75.0{^\circ}$ above the horizontal, as
illustrated in [link](#import-auto-id934168){.autogenerated-content}.
The fuse is timed to ignite the shell just as it reaches its highest
point above the ground. (a) Calculate the height at which the shell
explodes. (b) How much time passed between the launch of the shell and
the explosion? (c) What is the horizontal displacement of the shell when
it explodes?

::: {.tinysection}
[Strategy]{data-type="title"}
:::

Because air resistance is negligible for the unexploded shell, the
analysis method outlined above can be used. The motion can be broken
into horizontal and vertical motions in which ${a_{x} = 0}{}$ and
${a_{y} = –g}{}$. We can then define $x_{0}{}$ and $y_{0}{}$ to be zero
and solve for the desired quantities.

::: {.tinysection}
[Solution for (a)]{data-type="title"}
:::

By "height" we mean the altitude or vertical position $y{}$ above the
starting point. The highest point in any trajectory, called the apex, is
reached when ${v_{y} = 0}{}$. Since we know the initial and final
velocities as well as the initial position, we use the following
equation to find $y{}$:

::: {#eip-734 data-type="equation"}
$${{v_{y}^{2} = {v_{0y}^{2} - 2g}}({y - y_{0}})\text{.}}{}$$
:::

![The trajectory of a fireworks shell. The fuse is set to explode the
shell at the highest point in its trajectory, which is found to be at a
height of 233 m and 125 m away
horizontally.](images/Figure_03_04_03a.jpg){#import-auto-id934168}

Because $y_{0}{}$ and $v_{y}{}$ are both zero, the equation simplifies
to

::: {#eip-42 data-type="equation"}
$${{0 = {v_{0y}^{2} - 2}}\text{gy.}}{}$$
:::

Solving for $y{}$ gives

::: {#eip-256 data-type="equation"}
$${{y = \frac{v_{0y}^{2}}{2g}}\text{.}}{}$$
:::

Now we must find $v_{0y}{}$, the component of the initial velocity in
the *y*-direction. It is given by [v0y=v0sinθv0y=v0sinθ size 12{v rSub {
size 8{0y rSup} =v rSub {0 rSup size 12{\"sin\"θ}} {}]{.math
xmlns="http://www.w3.org/1998/Math/MathML" display="inline"}, where
$v_{0y}{}$ is the initial velocity of 70.0 m/s, and
${\theta_{0} = 75.0{^\circ}}{}$ is the initial angle. Thus,

::: {#eip-677 data-type="equation"}
$${{v_{0y} = v_{0}}\ \text{sin}\ {\theta_{0} = (}\text{70.0\ m/s})(\text{sin\ 75°}{) = \text{67.6\ m/s.}}}{}$$
:::

and $y{}$ is

::: {#eip-512 data-type="equation"}
$${y = \frac{(\text{67}\text{.6\ m/s})^{2}}{2(9\text{.}\text{80\ m}\text{/s}^{2})}},$$
:::

so that

::: {#eip-310 data-type="equation"}
$${{y = \text{233}}\operatorname{}\text{m.}}{}$$
:::

::: {.tinysection}
[Discussion for (a)]{data-type="title"}
:::

Note that because up is positive, the initial velocity is positive, as
is the maximum height, but the acceleration due to gravity is negative.
Note also that the maximum height depends only on the vertical component
of the initial velocity, so that any projectile with a 67.6 m/s initial
vertical component of velocity will reach a maximum height of 233 m
(neglecting air resistance). The numbers in this example are reasonable
for large fireworks displays, the shells of which do reach such heights
before exploding. In practice, air resistance is not completely
negligible, and so the initial velocity would have to be somewhat larger
than that given to reach the same height.

::: {.tinysection}
[Solution for (b)]{data-type="title"}
:::

As in many physics problems, there is more than one way to solve for the
time to the highest point. In this case, the easiest method is to use
${{y = {y_{0} + \frac{1}{2}}}({v_{0y} + v_{y}})t}{}$. Because $y_{0}{}$
is zero, this equation reduces to simply

::: {#eip-383 data-type="equation"}
$${{y = \frac{1}{2}}({v_{0y} + v_{y}})t}\text{.}{}$$
:::

Note that the final vertical velocity, $v_{y}{}$, at the highest point
is zero. Thus,

::: {#eip-50 data-type="equation"}
$$\begin{array}{lll}
t & = & {\frac{2y}{({v_{0y} + v_{y}})} = \frac{{2(\text{233\ m}})}{(\text{67.6\ m/s})}} \\
 & = & {\text{6.90\ s}\text{.}} \\
\end{array}{}$$
:::

::: {.tinysection}
[Discussion for (b)]{data-type="title"}
:::

This time is also reasonable for large fireworks. When you are able to
see the launch of fireworks, you will notice several seconds pass before
the shell explodes. (Another way of finding the time is by using
${{y = {y_{0} + v_{0y}}}{t - \frac{1}{2}}\text{gt}^{2}}{}$, and solving
the quadratic equation for $t{}$.)

::: {.tinysection}
[Solution for (c)]{data-type="title"}
:::

Because air resistance is negligible, ${a_{x} = 0}{}$ and the horizontal
velocity is constant, as discussed above. The horizontal displacement is
horizontal velocity multiplied by time as given by
${{x = {x_{0} + v_{x}}}t}{}$, where $x_{0}{}$ is equal to zero:

::: {#eip-675 data-type="equation"}
$${{x = v_{x}}t\text{,}}{}$$
:::

where $v_{x}{}$ is the **x**-component of the velocity, which is given
by ${{v_{x} = v_{0}}\ \text{cos}\ \theta_{0}\text{.}}{}$ Now,

::: {#eip-884 data-type="equation"}
$${{v_{x} = v_{0}}\ \text{cos}\ {\theta_{0} = (}\text{70}\text{.}0\ m/s)(\text{cos\ 75.0°}{) = \text{18}}\text{.}1\ m/s.}{}$$
:::

The time $t{}$ for both motions is the same, and so $x{}$ is

::: {#eip-685 data-type="equation"}
$${{x = (}\text{18}\text{.}1\ m/s)(6\text{.}\text{90\ s}{) = \text{125\ m.}}}{}$$
:::

::: {.tinysection}
[Discussion for (c)]{data-type="title"}
:::

The horizontal motion is a constant velocity in the absence of air
resistance. The horizontal displacement found here could be useful in
keeping the fireworks fragments from falling on spectators. Once the
shell explodes, air resistance has a major effect, and many fragments
will land directly below.
:::

In solving part (a) of the preceding example, the expression we found
for $y{}$ is valid for any projectile motion where air resistance is
negligible. Call the maximum height ${y = h}{}$; then,

::: {#eip-803 data-type="equation"}
$${{h = \frac{v_{0y}^{2}}{2g}}\text{.}}{}$$
:::

This equation defines the **maximum height of a projectile** and depends
only on the vertical component of the initial velocity.

::: {#fs-id1479427 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Defining a Coordinate System
:::

It is important to set up a coordinate system when analyzing projectile
motion. One part of defining the coordinate system is to define an
origin for the $x{}$ and $y{}$ positions. Often, it is convenient to
choose the initial position of the object as the origin such that
${x_{0} = 0}{}$ and ${y_{0} = 0}{}$. It is also important to define the
positive and negative directions in the $x{}$ and $y{}$ directions.
Typically, we define the positive vertical direction as upwards, and the
positive horizontal direction is usually the direction of the object\'s
motion. When this is the case, the vertical acceleration, $g{}$, takes a
negative value (since it is directed downwards towards the Earth).
However, it is occasionally useful to define the coordinates
differently. For example, if you are analyzing the motion of a ball
thrown downwards from the top of a cliff, it may make sense to define
the positive direction downwards since the motion of the ball is solely
in the downwards direction. If this is the case, $g{}$ takes a positive
value.
:::

::: {#fs-id708626 data-type="example"}
::: {data-type="title"}
Calculating Projectile Motion: Hot Rock Projectile
:::

Kilauea in Hawaii is the world\'s most continuously active volcano. Very
active volcanoes characteristically eject red-hot rocks and lava rather
than smoke and ash. Suppose a large rock is ejected from the volcano
with a speed of 25.0 m/s and at an angle $\text{35.0°}{}$ above the
horizontal, as shown in
[link](#import-auto-id1817519){.autogenerated-content}. The rock strikes
the side of the volcano at an altitude 20.0 m lower than its starting
point. (a) Calculate the time it takes the rock to follow this path. (b)
What are the magnitude and direction of the rock\'s velocity at impact?

![The trajectory of a rock ejected from the Kilauea
volcano.](images/Figure_03_04_04a.jpg){#import-auto-id1817519}

::: {.tinysection}
[Strategy]{data-type="title"}
:::

Again, resolving this two-dimensional motion into two independent
one-dimensional motions will allow us to solve for the desired
quantities. The time a projectile is in the air is governed by its
vertical motion alone. We will solve for $t{}$ first. While the rock is
rising and falling vertically, the horizontal motion continues at a
constant velocity. This example asks for the final velocity. Thus, the
vertical and horizontal results will be recombined to obtain $v{}$ and
$\theta_{v}{}$ at the final time $t{}$ determined in the first part of
the example.

::: {.tinysection}
[Solution for (a)]{data-type="title"}
:::

While the rock is in the air, it rises and then falls to a final
position 20.0 m lower than its starting altitude. We can find the time
for this by using

::: {#eip-895 data-type="equation"}
$${{y = {y_{0} + v_{0y}}}{t - \frac{1}{2}}\text{gt}^{2}\text{.}}{}$$
:::

If we take the initial position $y_{0}{}$ to be zero, then the final
position is ${{y = {- \text{20}}}\text{.0\ \ m}\text{.}}{}$ Now the
initial vertical velocity is the vertical component of the initial
velocity, found from ${{v_{0y} = v_{0}}\ \text{sin}\ \theta_{0}}{}$ =
(${\text{25}\text{.}\text{0~m/s}}{}$)($\text{sin\ 35.0°}{}$) =
${\text{14}\text{.}\text{3~m/s}}{}$. Substituting known values yields

::: {#eip-722 data-type="equation"}
$${{{- \text{20}}\text{.}0\ m{= (}\text{14}\text{.}3\ m/s){t - \left( {4\text{.}\text{90\ m/s}^{2}} \right)}t^{2}}\text{.}}{}$$
:::

Rearranging terms gives a quadratic equation in $t{}$:

::: {#eip-931 data-type="equation"}
$${\left( {4\text{.}\text{90\ m/s}^{2}} \right){t^{2} - \left( {\text{14}\text{.}\text{3\ m/s}} \right)}{{t - \left( \text{20.0\ m} \right)} = 0.}}{}$$
:::

This expression is a quadratic equation of the form
${at}^{2} + {bt} + c = 0$, where the constants are $a = 4.90$,
$b = –14.3$, and $c = –20.0.$ Its solutions are given by the quadratic
formula:

::: {#eip-880 data-type="equation"}
$${{t = \frac{{- b} \pm \sqrt{{b^{2} - 4}\text{ac}}}{\text{2}\text{a}}}\text{.}}{}$$
:::

This equation yields two solutions: $t = 3.96$ and $t = –1.03$. (It is
left as an exercise for the reader to verify these solutions.) The time
is $t = 3.96\ \text{s}$ or $–1.03\ \text{s}$. The negative value of time
implies an event before the start of motion, and so we discard it. Thus,

::: {#eip-267 data-type="equation"}
$${{t = 3}\text{.}\text{96\ s}\text{.}}{}$$
:::

::: {.tinysection}
[Discussion for (a)]{data-type="title"}
:::

The time for projectile motion is completely determined by the vertical
motion. So any projectile that has an initial vertical velocity of 14.3
m/s and lands 20.0 m below its starting altitude will spend 3.96 s in
the air.

::: {.tinysection}
[Solution for (b)]{data-type="title"}
:::

From the information now in hand, we can find the final horizontal and
vertical velocities $v_{x}{}$ and $v_{y}{}$ and combine them to find the
total velocity $v{}$ and the angle $\theta_{0}{}$ it makes with the
horizontal. Of course, $v_{x}{}$ is constant so we can solve for it at
any horizontal location. In this case, we chose the starting point since
we know both the initial velocity and initial angle. Therefore:

::: {#eip-873 data-type="equation"}
$${{v_{x} = v_{0}}\ \text{cos}\ {\theta_{0} = (}\text{25}\text{.}0\ m/s)(\text{cos\ 35°}{) = \text{20}}\text{.}5\ m/s.}{}$$
:::

The final vertical velocity is given by the following equation:

::: {#eip-168 data-type="equation"}
$${v_{y} = {v_{0y} - \text{gt,}}}{}$$
:::

where $v_{0y}{}$ was found in part (a) to be
${\text{14}\text{.}\text{3~m/s}}{}$. Thus,

::: {#eip-113 data-type="equation"}
$${{v_{y} = \text{14}}\text{.}3\ m/s{- (}9\text{.}\text{80\ m/s}^{2})(3\text{.}\text{96\ s})}{}$$
:::

so that

::: {#eip-571 data-type="equation"}
$${{v_{y} = {- \text{24}}}\text{.}5\ m/s.}{}$$
:::

To find the magnitude of the final velocity $v{}$ we combine its
perpendicular components, using the following equation:

::: {#eip-394 data-type="equation"}
$${{v = \sqrt{v_{x}^{2} + v_{y}^{2}}} = \sqrt{(\text{20}\text{.}5\ m/s{{)^{2} + (} - \text{24}}\text{.}5\ m/s)^{2}}\text{,}}{}$$
:::

which gives

::: {#eip-60 data-type="equation"}
$${{v = \text{31}}\text{.}9\ m/s.}{}$$
:::

The direction $\theta_{v}{}$ is found from the equation:

::: {#eip-353 data-type="equation"}
$${{\theta_{v} = \text{tan}^{- 1}}({v_{y}/v_{x}})}{}$$
:::

so that

::: {#eip-589 data-type="equation"}
$${{\theta_{v} = \text{tan}^{- 1}}{( - \text{24}}\text{.}{5/\text{20}}\text{.}5{) = \text{tan}^{- 1}}{( - 1}\text{.}\text{19})\text{.}}{}$$
:::

Thus,

::: {#eip-379 data-type="equation"}
$${{\theta_{v} = {- \text{50}}}\text{.}1{{^\circ}\text{.}}}{}$$
:::

::: {.tinysection}
[Discussion for (b)]{data-type="title"}
:::

The negative angle means that the velocity is
${\text{50}\text{.}1{^\circ}}{}$ below the horizontal. This result is
consistent with the fact that the final vertical velocity is negative
and hence downward---as you would expect because the final altitude is
20.0 m lower than the initial altitude. (See
[link](#import-auto-id1817519){.autogenerated-content}.)
:::

One of the most important things illustrated by projectile motion is
that vertical and horizontal motions are independent of each other.
Galileo was the first person to fully comprehend this characteristic. He
used it to predict the range of a projectile. On level ground, we define
[range]{#import-auto-id1751163 data-type="term"} to be the horizontal
distance $R{}$ traveled by a projectile. Galileo and many others were
interested in the range of projectiles primarily for military
purposes---such as aiming cannons. However, investigating the range of
projectiles can shed light on other interesting phenomena, such as the
orbits of satellites around the Earth. Let us consider projectile range
further.

![Trajectories of projectiles on level ground. (a) The greater the
initial speed $v_{0}{}$, the greater the range for a given initial
angle. (b) The effect of initial angle $\theta_{0}{}$ on the range of a
projectile with a given initial speed. Note that the range is the same
for $\text{15°}{}$ and $\text{75°}{}$, although the maximum heights of
those paths are
different.](images/Figure_03_04_05a.jpg){#import-auto-id1904800}

How does the initial velocity of a projectile affect its range?
Obviously, the greater the initial speed $v_{0}{}$, the greater the
range, as shown in
[link](#import-auto-id1904800){.autogenerated-content}(a). The initial
angle $\theta_{0}{}$ also has a dramatic effect on the range, as
illustrated in
[link](#import-auto-id1904800){.autogenerated-content}(b). For a fixed
initial speed, such as might be produced by a cannon, the maximum range
is obtained with ${\theta_{0} = \text{45°}}{}$. This is true only for
conditions neglecting air resistance. If air resistance is considered,
the maximum angle is approximately $\text{38°}{}$. Interestingly, for
every initial angle except $\text{45°}{}$, there are two angles that
give the same range---the sum of those angles is $\text{90°}{}$. The
range also depends on the value of the acceleration of gravity $g{}$.
The lunar astronaut Alan Shepherd was able to drive a golf ball a great
distance on the Moon because gravity is weaker there. The range $R{}$ of
a projectile on **level ground** for which air resistance is negligible
is given by

::: {#eip-240 data-type="equation"}
$${R = \frac{v_{0}^{2}\ \text{sin}\ {2\theta}_{0}}{g}}\text{,}{}$$
:::

where $v_{0}{}$ is the initial speed and $\theta_{0}{}$ is the initial
angle relative to the horizontal. The proof of this equation is left as
an end-of-chapter problem (hints are given), but it does fit the major
features of projectile range as described.

When we speak of the range of a projectile on level ground, we assume
that $R{}$ is very small compared with the circumference of the Earth.
If, however, the range is large, the Earth curves away below the
projectile and acceleration of gravity changes direction along the path.
The range is larger than predicted by the range equation given above
because the projectile has farther to fall than it would on level
ground. (See [link](#import-auto-id1645881){.autogenerated-content}.) If
the initial speed is great enough, the projectile goes into orbit. This
possibility was recognized centuries before it could be accomplished.
When an object is in orbit, the Earth curves away from underneath the
object at the same rate as it falls. The object thus falls continuously
but never hits the surface. These and other aspects of orbital motion,
such as the rotation of the Earth, will be covered analytically and in
greater depth later in this text.

Once again we see that thinking about one topic, such as the range of a
projectile, can lead us to others, such as the Earth orbits. In
[Addition of Velocities](/m55089), we will examine the addition of
velocities, which is another important aspect of two-dimensional
kinematics and will also yield insights beyond the immediate topic.

![Projectile to satellite. In each case shown here, a projectile is
launched from a very high tower to avoid air resistance. With increasing
initial speed, the range increases and becomes longer than it would be
on level ground because the Earth curves away underneath its path. With
a large enough initial speed, orbit is
achieved.](images/Figure_03_04_06a.jpg){#import-auto-id1645881}

::: {#eip-89 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Projectile Motion
:::

Blast a Buick out of a cannon! Learn about projectile motion by firing
various objects. Set the angle, initial speed, and mass. Add air
resistance. Make a game out of this simulation by trying to hit a
target.

```{=html}
<figure id="eip-id1462984fig">
```
::: {#fs-id1167061400916 data-type="media" data-alt="This simulation provides an opportunity to learn through experimentation with projectiles."}
```{=html}
<iframe width="660" height="371.4" src="https://openstax.org/l/28prjctilemtion">
```
`<!-- no-selfclose -->`{=html}
```{=html}
</iframe>
```
:::

```{=html}
</figure>
```
:::

::: {#fs-id1619869 .ap-test-prep depth="1" element-type="ap-test-prep"}
### Test Prep for AP Courses { data-type="title"}

::: {#fs-id1316152 data-type="exercise" element-type="ap-test-prep"}
::: {#fs-id1749813 data-type="problem"}
In an experiment, a student launches a ball with an initial horizontal
velocity of 5.00 meters/sec at an elevation 2.00 meters above ground.
Draw and clearly label with appropriate values and units a graph of the
ball\'s horizontal velocity vs. time and the ball\'s vertical velocity
vs. time. The graph should cover the motion from the instant after the
ball is launched until the instant before it hits the ground. Assume the
downward direction is negative for this problem.
:::

`<!--<solution id="fs-id1479455"><para id="fs-id1593816">The time it will take for the ball to hit the ground is:</para>
<para id="fs-id2010337"><m:math display="block">
 <m:mrow>
  <m:mi>t</m:mi><m:mo>=</m:mo><m:msqrt>
   <m:mrow>
    <m:mfrac>
     <m:mrow>
      <m:mn>2</m:mn><m:mi>h</m:mi>
     </m:mrow>
     <m:mi>g</m:mi>
    </m:mfrac>

   </m:mrow>
  </m:msqrt>
  <m:mo>=</m:mo><m:mn>0.639</m:mn><m:mtext>&#160;</m:mtext><m:mi>s</m:mi>
 </m:mrow>
</m:math>
</para><para id="fs-id1657595">The horizontal velocity graph should simply be a horizontal straight line starting at t = 0 and a velocity of 5.00 meters/sec on the vertical axis, then extending in the positive horizontal direction until t = 0.639 s.</para>
<para id="fs-id1960787">The vertical velocity graph should have an initial value of zero at t = 0. The velocity should show a linear increase in the negative direction until it reaches a value:</para>
<para id="fs-id2172350"><m:math display="block">
 <m:mrow>
  <m:msup>
   <m:mi>v</m:mi>
   <m:mo>&#8242;</m:mo>
  </m:msup>
  <m:mtext>&#160;</m:mtext><m:mo>=</m:mo><m:mtext>&#160;</m:mtext><m:mo>-</m:mo><m:mtext>&#160;</m:mtext><m:mi>g</m:mi><m:mi>t</m:mi><m:mtext>&#160;</m:mtext><m:mo>=</m:mo><m:mtext>&#160;</m:mtext><m:mo>-</m:mo><m:mn>6.26</m:mn><m:mfrac>
   <m:mtext>m</m:mtext>
   <m:mtext>s</m:mtext>
  </m:mfrac>

 </m:mrow>
</m:math>
</para><para id="fs-id1301141">at t = 0.639 s.</para>
</solution>-->`{=html}
:::
:::

::: {#fs-id1843457-summary depth="1"}
### Summary { data-type="title"}

-   [Projectile motion is the motion of an object through the air that
    is subject only to the acceleration of
    gravity.]{#import-auto-id1677012}
-   [To solve projectile motion problems, perform the following
    steps:]{#import-auto-id1786765}
    1.  [Determine a coordinate system. Then, resolve the position
        and/or velocity of the object in the horizontal and vertical
        components. The components of position $\mathbf{s}{}$ are given
        by the quantities $x{}$ and $y{}$, and the components of the
        velocity $\mathbf{v}{}$ are given by
        ${{v_{x} = v}\ \text{cos}\ \theta}{}$ and
        ${{v_{y} = v}\ \text{sin}\ \theta}{}$, where $v{}$ is the
        magnitude of the velocity and $\theta{}$ is its
        direction.]{#import-auto-id1830314}
    2.  [Analyze the motion of the projectile in the horizontal
        direction using the following
        equations:]{#import-auto-id1830316}
        ::: {#eip-898 data-type="equation"}
        $${\text{Horizontal\ motion}({a_{x} = 0})}{}$$
        :::

        ::: {#eip-236 data-type="equation"}
        $${{x = {x_{0} + v_{x}}}t}{}$$
        :::

        ::: {#eip-612 data-type="equation"}
        $${{{v_{x} = v_{0x}} = \textbf{v}_{\text{x}}} = \text{velocity\ is\ a\ constant.}}{}$$
        :::
    3.  [Analyze the motion of the projectile in the vertical direction
        using the following equations:]{#import-auto-id1939082}
        ::: {#import-auto-id1939084 data-type="equation"}
        $${\text{Vertical\ motion}(\text{Assuming\ positive\ direction\ is\ up;}\ {{a_{y} = {- g}} = {- 9}}\text{.}\text{80\ m}\text{/s}^{2})}{}$$
        :::

        ::: {#import-auto-id1492830 data-type="equation"}
        $${{y = {y_{0} + \frac{1}{2}}}({v_{0y} + v_{y}})t}{}$$
        :::

        ::: {#import-auto-id2022844 data-type="equation"}
        $${v_{y} = {v_{0y} - \text{gt}}}{}$$
        :::

        ::: {#import-auto-id1677876 data-type="equation"}
        $${{y = {y_{0} + v_{0y}}}{t - \frac{1}{2}}\text{gt}^{2}}{}$$
        :::

        ::: {#import-auto-id1653540 data-type="equation"}
        $${{v_{y}^{2} = {v_{0y}^{2} - 2g}}({y - y_{0}})}.{}$$
        :::
    4.  [Recombine the horizontal and vertical components of location
        and/or velocity using the following
        equations:]{#import-auto-id1552181}
        ::: {#import-auto-id2092332 data-type="equation"}
        $${s = \sqrt{x^{2} + y^{2}}}{}$$
        :::

        ::: {#import-auto-id2282348 data-type="equation"}
        $${{\theta = \text{tan}^{- 1}}({y/x})}{}$$
        :::

        ::: {#import-auto-id2274748 data-type="equation"}
        $${v = \sqrt{v_{x}^{2} + v_{y}^{2}}}{}$$
        :::

        ::: {#import-auto-id1979208 data-type="equation"}
        $${{\theta_{\text{v}} = \text{tan}^{- 1}}({v_{y}/v_{x}})}{}.$$
        :::
-   [The maximum height $h{}$ of a projectile launched with initial
    vertical velocity $v_{0y}{}$ is given by]{#import-auto-id1888635}
    ::: {#import-auto-id1534227 data-type="equation"}
    $${h = \frac{v_{0y}^{2}}{2g}}{}.$$
    :::
-   [The maximum horizontal distance traveled by a projectile is called
    the **range**. The range $R{}$ of a projectile on level ground
    launched at an angle $\theta_{0}{}$ above the horizontal with
    initial speed $v_{0}{}$ is given by]{#import-auto-id1823593}
    ::: {#import-auto-id1951750 data-type="equation"}
    $${R = \frac{v_{0}^{2}\ \text{sin}\ {2\theta}_{0}}{g}}{}.$$
    :::
:::

::: {#fs-id2865659 .conceptual-questions depth="1" element-type="conceptual-questions"}
### Conceptual Questions { data-type="title"}

::: {#fs-id2183300 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id2183302 data-type="problem"}
Answer the following questions for projectile motion on level ground
assuming negligible air resistance (the initial angle being neither
$\text{0°}{}$ nor $\text{90°}{}$): (a) Is the velocity ever zero? (b)
When is the velocity a minimum? A maximum? (c) Can the velocity ever be
the same as the initial velocity at a time other than at ${t = 0}{}$?
(d) Can the speed ever be the same as the initial speed at a time other
than at ${t = 0}{}$?
:::
:::

::: {#fs-id1638420 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1638423 data-type="problem"}
Answer the following questions for projectile motion on level ground
assuming negligible air resistance (the initial angle being neither
$\text{0°}{}$ nor $\text{90°}{}$): (a) Is the acceleration ever zero?
(b) Is the acceleration ever in the same direction as a component of
velocity? (c) Is the acceleration ever opposite in direction to a
component of velocity?
:::
:::

::: {#fs-id2062475 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id2062477 data-type="problem"}
For a fixed initial speed, the range of a projectile is determined by
the angle at which it is fired. For all but the maximum, there are two
angles that give the same range. Considering factors that might affect
the ability of an archer to hit a target, such as wind, explain why the
smaller angle (closer to the horizontal) is preferable. When would it be
necessary for the archer to use the larger angle? Why does the punter in
a football game use the higher trajectory?
:::
:::

::: {#fs-id1875651 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1875652 data-type="problem"}
During a lecture demonstration, a professor places two coins on the edge
of a table. She then flicks one of the coins horizontally off the table,
simultaneously nudging the other over the edge. Describe the subsequent
motion of the two coins, in particular discussing whether they hit the
floor at the same time.
:::
:::
:::

::: {#fs-id1875655 .problems-exercises depth="1" element-type="problems-exercises"}
### Problems & Exercises { data-type="title"}

::: {#fs-id1923898 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1105650 data-type="problem"}
A projectile is launched at ground level with an initial speed of 50.0
m/s at an angle of $30.0{^\circ}$ above the horizontal. It strikes a
target above the ground 3.00 seconds later. What are the $x{}$ and $y{}$
distances from where the projectile was launched to where it lands?
:::

::: {#fs-id1543587 data-type="solution"}
$\begin{array}{lll}
x & = & {\text{1.30\ m} \times 10^{2}} \\
y & = & {\text{30}\text{.9\ m.}} \\
\end{array}$
:::
:::

::: {#fs-id1275043 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1019417 data-type="problem"}
A ball is kicked with an initial velocity of 16 m/s in the horizontal
direction and 12 m/s in the vertical direction. (a) At what speed does
the ball hit the ground? (b) For how long does the ball remain in the
air? (c)What maximum height is attained by the ball?
:::
:::

::: {#fs-id2889503 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1790979 data-type="problem"}
A ball is thrown horizontally from the top of a 60.0-m building and
lands 100.0 m from the base of the building. Ignore air resistance. (a)
How long is the ball in the air? (b) What must have been the initial
horizontal component of the velocity? (c) What is the vertical component
of the velocity just before the ball hits the ground? (d) What is the
velocity (including both the horizontal and vertical components) of the
ball just before it hits the ground?
:::

::: {#fs-id1945253 data-type="solution"}
\(a\) 3.50 s

\(b\) 28.6 m/s (c) 34.3 m/s

\(d\) 44.7 m/s, $50.2{^\circ}$ below horizontal
:::
:::

::: {#fs-id2197387 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2261404 data-type="problem"}
\(a\) A daredevil is attempting to jump his motorcycle over a line of
buses parked end to end by driving up a $\text{32°}{}$ ramp at a speed
of ${\text{40}\text{.}\text{0~m/s~}(\text{144~km/h})}{}$. How many buses
can he clear if the top of the takeoff ramp is at the same height as the
bus tops and the buses are 20.0 m long? (b) Discuss what your answer
implies about the margin of error in this act---that is, consider how
much greater the range is than the horizontal distance he must travel to
miss the end of the last bus. (Neglect air resistance.)
:::
:::

::: {#fs-id1420192 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1078714 data-type="problem"}
An archer shoots an arrow at a 75.0 m distant target; the bull\'s-eye of
the target is at same height as the release height of the arrow. (a) At
what angle must the arrow be released to hit the bull\'s-eye if its
initial speed is 35.0 m/s? In this part of the problem, explicitly show
how you follow the steps involved in solving projectile motion problems.
(b) There is a large tree halfway between the archer and the target with
an overhanging horizontal branch 3.50 m above the release height of the
arrow. Will the arrow go over or under the branch?
:::

::: {#fs-id1970452 data-type="solution"}
\(a\) ${\text{18}\text{.}\text{4°}}{}$

\(b\) The arrow will go over the branch.
:::
:::

::: {#fs-id1934878 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2226553 data-type="problem"}
A rugby player passes the ball 7.00 m across the field, where it is
caught at the same height as it left his hand. (a) At what angle was the
ball thrown if its initial speed was 12.0 m/s, assuming that the smaller
of the two possible angles was used? (b) What other angle gives the same
range, and why would it not be used? (c) How long did this pass take?
:::
:::

::: {#fs-id2126267 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2889922 data-type="problem"}
Verify the ranges for the projectiles in
[link](#import-auto-id1904800){.autogenerated-content}(a) for
${\theta = \text{45°}}{}$ and the given initial velocities.
:::

::: {#fs-id1903883 data-type="solution"}
[R=v02 sin2θ0gFor θ=45°, R=v02gR=v02 sin2θ0gFor θ=45°, R=v02galignl {
stack { size 12{R= { {v rSub { size 8{0} rSup { size 8{2} } } \"sin\"2θ
rSub { size 8{0} } } over {g} } } {} \# \"For \"θ=\"45\"°: {} \# R= { {v
rSub { size 8{0} rSup { size 8{2} } } } over {g} } {} } } {}]{.math
xmlns="http://www.w3.org/1998/Math/MathML" display="inline"}

${R = 91.8\ \text{m}}{}$ for ${v_{0} = 30\ \text{m/s}}{}$;
${R = 163\ \text{m}}{}$ for ${v_{0} = 40\ \text{m/s}}{}$;
${R = 255\ \text{m}}{}$ for ${v_{0} = 50\ \text{m/s}}{}$.
:::
:::

::: {#fs-id2214647 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2214182 data-type="problem"}
Verify the ranges shown for the projectiles in
[link](#import-auto-id1904800){.autogenerated-content}(b) for an initial
velocity of 50 m/s at the given initial angles.
:::
:::

::: {#fs-id2905201 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1851487 data-type="problem"}
The cannon on a battleship can fire a shell a maximum distance of 32.0
km. (a) Calculate the initial velocity of the shell. (b) What maximum
height does it reach? (At its highest, the shell is above 60% of the
atmosphere---but air resistance is not really negligible as assumed to
make this problem easier.) (c) The ocean is not flat, because the Earth
is curved. Assume that the radius of the Earth is
${6\text{.}{\text{37} \times \text{10}^{3}}\ \text{km}}{}$. How many
meters lower will its surface be 32.0 km from the ship along a
horizontal line parallel to the surface at the ship? Does your answer
imply that error introduced by the assumption of a flat Earth in
projectile motion is significant here?
:::

::: {#fs-id2075683 data-type="solution"}
\(a\) 560 m/s

\(b\) ${8\text{.}{\text{00} \times \text{10}^{3}}\ \text{m}}{}$

\(c\) 80.0 m. This error is not significant because it is only 1% of the
answer in part (b).
:::
:::

::: {#fs-id1925728 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2282381 data-type="problem"}
An arrow is shot from a height of 1.5 m toward a cliff of height $H{}$.
It is shot with a velocity of 30 m/s at an angle of $\text{60°}{}$ above
the horizontal. It lands on the top edge of the cliff 4.0 s later. (a)
What is the height of the cliff? (b) What is the maximum height reached
by the arrow along its trajectory? (c) What is the arrow\'s impact speed
just before hitting the cliff?
:::
:::

::: {#fs-id1745072 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2275266 data-type="problem"}
In the standing broad jump, one squats and then pushes off with the legs
to see how far one can jump. Suppose the extension of the legs from the
crouch position is 0.600 m and the acceleration achieved from this
position is 1.25 times the acceleration due to gravity, $g{}$. How far
can they jump? State your assumptions. (Increased range can be achieved
by swinging the arms in the direction of the jump.)
:::

::: {#fs-id2864553 data-type="solution"}
1.50 m, assuming launch angle of $45{^\circ}$
:::
:::

::: {#fs-id1875777 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2864558 data-type="problem"}
The world long jump record is 8.95 m (Mike Powell, USA, 1991). Treated
as a projectile, what is the maximum range obtainable by a person if he
has a take-off speed of 9.5 m/s? State your assumptions.
:::
:::

::: {#fs-id2254986 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1543443 data-type="problem"}
Serving at a speed of 170 km/h, a tennis player hits the ball at a
height of 2.5 m and an angle $\theta{}$ below the horizontal. The
baseline from which the ball is served is 11.9 m from the net, which is
0.91 m high. What is the angle $\theta{}$ such that the ball just
crosses the net? Will the ball land in the service box, which has an
outermost service line is 6.40 m from the net?
:::

::: {#fs-id722706 data-type="solution"}
${\theta = 6.1{^\circ}}{}$

yes, the ball lands at 5.3 m from the net
:::
:::

::: {#fs-id2173828 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2088349 data-type="problem"}
A football quarterback is moving straight backward at a speed of 2.00
m/s when he throws a pass to a player 18.0 m straight downfield. (a) If
the ball is thrown at an angle of $\text{25°}{}$ relative to the ground
and is caught at the same height as it is released, what is its initial
speed relative to the ground? (b) How long does it take to get to the
receiver? (c) What is its maximum height above its point of release?
:::
:::

::: {#fs-id1796436 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1979282 data-type="problem"}
Gun sights are adjusted to aim high to compensate for the effect of
gravity, effectively making the gun accurate only for a specific range.
(a) If a gun is sighted to hit targets that are at the same height as
the gun and 100.0 m away, how low will the bullet hit if aimed directly
at a target 150.0 m away? The muzzle velocity of the bullet is 275 m/s.
(b) Discuss qualitatively how a larger muzzle velocity would affect this
problem and what would be the effect of air resistance.
:::

::: {#fs-id2175653 data-type="solution"}
\(a\) −0.486 m

\(b\) The larger the muzzle velocity, the smaller the deviation in the
vertical direction, because the time of flight would be smaller. Air
resistance would have the effect of decreasing the time of flight,
therefore increasing the vertical deviation.
:::
:::

::: {#fs-id2177814 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1781566 data-type="problem"}
An eagle is flying horizontally at a speed of 3.00 m/s when the fish in
her talons wiggles loose and falls into the lake 5.00 m below. Calculate
the velocity of the fish relative to the water when it hits the water.
:::
:::

::: {#fs-id1914025 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2057849 data-type="problem"}
An owl is carrying a mouse to the chicks in its nest. Its position at
that time is 4.00 m west and 12.0 m above the center of the 30.0 cm
diameter nest. The owl is flying east at 3.50 m/s at an angle
$30.0{^\circ}{}$ below the horizontal when it accidentally drops the
mouse. Is the owl lucky enough to have the mouse hit the nest? To answer
this question, calculate the horizontal position of the mouse when it
has fallen 12.0 m.
:::

::: {#fs-id2042074 data-type="solution"}
4.23 m. No, the owl is not lucky; he misses the nest.
:::
:::

::: {#fs-id1403577 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2865734 data-type="problem"}
Suppose a soccer player kicks the ball from a distance 30 m toward the
goal. Find the initial speed of the ball if it just passes over the
goal, 2.4 m above the ground, given the initial direction to be
$\text{40°}{}$ above the horizontal.
:::
:::

::: {#fs-id2260735 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1789803 data-type="problem"}
Can a goalkeeper at her/ his goal kick a soccer ball into the
opponent\'s goal without the ball touching the ground? The distance will
be about 95 m. A goalkeeper can give the ball a speed of 30 m/s.
:::

::: {#fs-id1985242 data-type="solution"}
No, the maximum range (neglecting air resistance) is about 92 m.
:::
:::

::: {#fs-id1437858 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1891285 data-type="problem"}
The free throw line in basketball is 4.57 m (15 ft) from the basket,
which is 3.05 m (10 ft) above the floor. A player standing on the free
throw line throws the ball with an initial speed of 8.15 m/s, releasing
it at a height of 2.44 m (8 ft) above the floor. At what angle above the
horizontal must the ball be thrown to exactly hit the basket? Note that
most players will use a large initial angle rather than a flat shot
because it allows for a larger margin of error. Explicitly show how you
follow the steps involved in solving projectile motion problems.
:::
:::

::: {#fs-id1827481 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1750926 data-type="problem"}
In 2007, Michael Carter (U.S.) set a world record in the shot put with a
throw of 24.77 m. What was the initial speed of the shot if he released
it at a height of 2.10 m and threw it at an angle of $38.0{^\circ}{}$
above the horizontal? (Although the maximum distance for a projectile on
level ground is achieved at $\text{45°}{}$ when air resistance is
neglected, the actual angle to achieve maximum range is smaller; thus,
$\text{38°}{}$ will give a longer range than $\text{45°}{}$ in the shot
put.)
:::

::: {#fs-id1630701 data-type="solution"}
15.0 m/s
:::
:::

::: {#fs-id1670278 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1945400 data-type="problem"}
A basketball player is running at ${5\text{.}\text{00~m/s}}{}$ directly
toward the basket when he jumps into the air to dunk the ball. He
maintains his horizontal velocity. (a) What vertical velocity does he
need to rise 0.750 m above the floor? (b) How far from the basket
(measured in the horizontal direction) must he start his jump to reach
his maximum height at the same time as he reaches the basket?
:::
:::

::: {#fs-id1779635 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1637691 data-type="problem"}
A football player punts the ball at a $45.0{^\circ}{}$ angle. Without an
effect from the wind, the ball would travel 60.0 m horizontally. (a)
What is the initial speed of the ball? (b) When the ball is near its
maximum height it experiences a brief gust of wind that reduces its
horizontal velocity by 1.50 m/s. What distance does the ball travel
horizontally?
:::

::: {#fs-id1545352 data-type="solution"}
\(a\) 24.2 m/s

\(b\) The ball travels a total of 57.4 m with the brief gust of wind.
:::
:::

::: {#fs-id2046931 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2241558 data-type="problem"}
Prove that the trajectory of a projectile is parabolic, having the form
${y = {\text{ax} + \text{bx}^{2}}}{}$. To obtain this expression, solve
the equation ${x = v_{0x}t}{}$ for $t{}$ and substitute it into the
expression for ${{y = v_{0y}}t–({1/2})\text{gt}^{2}}{}$ (These equations
describe the $x{}$ and $y{}$ positions of a projectile that starts at
the origin.) You should obtain an equation of the form
${y = {\text{ax} + \text{bx}^{2}}}{}$ where $a{}$ and $b{}$ are
constants.
:::
:::

::: {#fs-id2133758 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2890360 data-type="problem"}
Derive ${R = \frac{v_{0}^{2}\ \text{sin}\ 2\theta_{0}}{g}}{}$ for the
range of a projectile on level ground by finding the time $t{}$ at which
$y{}$ becomes zero and substituting this value of $t{}$ into the
expression for ${x - x_{0}}{}$, noting that ${R = {x - x_{0}}}{}$
:::

::: {#eip-id2932521 data-type="solution"}
${{{{y - y_{0}} = 0} = v_{0y}}{t - \frac{1}{2}}{{gt}^{2} = (}v_{0}\ \text{sin}\ \theta){t - \frac{1}{2}}{gt}^{2}}{}$,

so that ${t = \frac{2(v_{0}\ \text{sin}\ \theta)}{g}}{}$

${{{x - x_{0}} = v_{0x}}{t = (}v_{0}\ \text{cos}\ \theta){t = R},}{}$
and substituting for $t{}$ gives:

${{R = v_{0}}\ \text{cos}\ \theta{\left( \frac{{2v}_{0}\ \text{sin}\ \theta}{g} \right) = \frac{{2v}_{0}^{2}\ \text{sin}\ \theta\ \text{cos}\ \theta}{g}}}{}$

since
${2\ \text{sin}\ \theta\ \text{cos}\ {\theta = \text{sin}\ }2\theta,}{}$
the range is:

${R = \frac{{v_{0}}^{2}\ \text{sin}\ 2\theta}{g}}{}$.
:::
:::

::: {#fs-id1794949 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1626931 data-type="problem"}
::: {.tinysection}
[Unreasonable Results]{data-type="title"} (a) Find the maximum range of
a super cannon that has a muzzle velocity of 4.0 km/s. (b) What is
unreasonable about the range you found? (c) Is the premise unreasonable
or is the available equation inapplicable? Explain your answer. (d) If
such a muzzle velocity could be obtained, discuss the effects of air
resistance, thinning air with altitude, and the curvature of the Earth
on the range of the super cannon.
:::
:::
:::

::: {#fs-id1815382 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2255165 data-type="problem"}
::: {.tinysection}
[Construct Your Own Problem]{data-type="title"} Consider a ball tossed
over a fence. Construct a problem in which you calculate the ball\'s
needed initial velocity to just clear the fence. Among the things to
determine are; the height of the fence, the distance to the fence from
the point of release of the ball, and the height at which the ball is
released. You should also consider whether it is possible to choose the
initial speed for the ball and just calculate the angle at which it is
thrown. Also examine the possibility of multiple solutions given the
distances and heights you have chosen.
:::
:::
:::
:::

::: {data-type="glossary"}
### Glossary { data-type="glossary-title"}

air resistance
:   a frictional force that slows the motion of objects as they travel
    through the air; when solving basic physics problems, air resistance
    is assumed to be zero

```{=html}
<!-- -->
```

kinematics
:   the study of motion without regard to mass or force

```{=html}
<!-- -->
```

motion
:   displacement of an object as a function of time

```{=html}
<!-- -->
```

projectile
:   an object that travels through the air and experiences only
    acceleration due to gravity

```{=html}
<!-- -->
```

projectile motion
:   the motion of an object that is subject only to the acceleration of
    gravity

```{=html}
<!-- -->
```

range
:   the maximum horizontal distance that a projectile travels

```{=html}
<!-- -->
```

trajectory
:   the path of a projectile through the air
:::