Vectors, Scalars, and Coordinate Systems
----------------------------------------

![The motion of this Eclipse Concept jet can be described in terms of
the distance it has traveled (a scalar quantity) or its displacement in
a specific direction (a vector quantity). In order to specify the
direction of motion, its displacement must be described based on a
coordinate system. In this case, it may be convenient to choose motion
toward the left as positive motion (it is the forward direction for the
plane), although in many cases, the $x{}$-coordinate runs from left to
right, with motion to the right as positive and motion to the left as
negative. (credit: Armchair Aviator,
Flickr)](images/Figure_02_02_00.jpg){#import-auto-id1778274}

::: {#fs-id1545372 .learning-objectives depth="1"}
### Learning Objectives { data-type="title"}

By the end of this section, you will be able to:

-   Define and distinguish between scalar and vector quantities.
-   Assign a coordinate system for a scenario involving one-dimensional
    motion.

The information presented in this section supports the following AP®
learning objectives and science practices:

-   **3.A.1.2** The student is able to design an experimental
    investigation of the motion of an object.
:::

What is the difference between distance and displacement? Whereas
displacement is defined by both direction and magnitude, distance is
defined only by magnitude. Displacement is an example of a vector
quantity. Distance is an example of a scalar quantity. A
[vector]{#import-auto-id1738434 data-type="term"} is any quantity with
both *magnitude and direction*. Other examples of vectors include a
velocity of 90 km/h east and a force of 500 newtons straight down.

The direction of a vector in one-dimensional motion is given simply by a
plus ${( + )}{}$ or minus ${( - )}{}$ sign. Vectors are represented
graphically by arrows. An arrow used to represent a vector has a length
proportional to the vector\'s magnitude (e.g., the larger the magnitude,
the longer the length of the vector) and points in the same direction as
the vector.

Some physical quantities, like distance, either have no direction or
none is specified. A [scalar]{#import-auto-id1759638 data-type="term"}
is any quantity that has a magnitude, but no direction. For example, a
$\text{20ºC}$ temperature, the 250 kilocalories (250 Calories) of energy
in a candy bar, a 90 km/h speed limit, a person\'s 1.8 m height, and a
distance of 2.0 m are all scalars---quantities with no specified
direction. Note, however, that a scalar can be negative, such as a
$- \text{20ºC}$ temperature. In this case, the minus sign indicates a
point on a scale rather than a direction. Scalars are never represented
by arrows.

::: {#fs-id1655694 depth="1"}
### Coordinate Systems for One-Dimensional Motion {#coordinate-systems-for-one-dimensional-motion data-type="title"}

In order to describe the direction of a vector quantity, you must
designate a coordinate system within the reference frame. For
one-dimensional motion, this is a simple coordinate system consisting of
a one-dimensional coordinate line. In general, when describing
horizontal motion, motion to the right is usually considered positive,
and motion to the left is considered negative. With vertical motion,
motion up is usually positive and motion down is negative. In some
cases, however, as with the jet in
[link](#import-auto-id1778274){.autogenerated-content}, it can be more
convenient to switch the positive and negative directions. For example,
if you are analyzing the motion of falling objects, it can be useful to
define downwards as the positive direction. If people in a race are
running to the left, it is useful to define left as the positive
direction. It does not matter as long as the system is clear and
consistent. Once you assign a positive direction and start solving a
problem, you cannot change it.

![It is usually convenient to consider motion upward or to the right as
positive ${( + )}{}$ and motion downward or to the left as negative
${( - )}{}$.](images/Figure_02_02_00b.jpg){#import-auto-id1758074}

::: {#fs-id1788025 data-type="exercise" element-type="check-understanding" data-label=""}
::: {data-type="title"}
Check Your Understanding
:::

::: {#fs-id1765357 data-type="problem"}
A person\'s speed can stay the same as he or she rounds a corner and
changes direction. Given this information, is speed a scalar or a vector
quantity? Explain.
:::

::: {#fs-id2007066 data-type="solution"}
Speed is a scalar quantity. It does not change at all with direction
changes; therefore, it has magnitude only. If it were a vector quantity,
it would change as direction changes (even if its magnitude remained
constant).
:::
:::
:::

::: {#fs-id1784568-summary depth="1"}
### Section Summary { data-type="title"}

-   [A vector is any quantity that has magnitude and
    direction.]{#import-auto-id1534176}
-   [A scalar is any quantity that has magnitude but no
    direction.]{#import-auto-id1777731}
-   [Displacement and velocity are vectors, whereas distance and speed
    are scalars.]{#import-auto-id1416292}
-   [In one-dimensional motion, direction is specified by a plus or
    minus sign to signify left or right, up or down, and the
    like.]{#import-auto-id1739033}
:::

::: {#fs-id1799980 .conceptual-questions depth="1" element-type="conceptual-questions"}
### Conceptual Questions { data-type="title"}

::: {#fs-id1364975 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1770280 data-type="problem"}
A student writes, "*A bird that is diving for prey has a speed of*
${- \textit{10}\ {m/s}}{}$." What is wrong with the student\'s
statement? What has the student actually described? Explain.
:::
:::

::: {#fs-id1773292 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1706742 data-type="problem"}
What is the speed of the bird in
[link](#fs-id1364975){.autogenerated-content}?
:::
:::

::: {#fs-id1247502 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1777549 data-type="problem"}
Acceleration is the change in velocity over time. Given this
information, is acceleration a vector or a scalar quantity? Explain.
:::
:::

::: {#fs-id1548043 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1778185 data-type="problem"}
A weather forecast states that the temperature is predicted to be
${- 5ºC}{}$ the following day. Is this temperature a vector or a scalar
quantity? Explain.
:::
:::
:::

::: {#fs-id2066209 .note data-type="note"}
::: {data-type="title"}
Switching Reference Frames
:::

A fundamental tenet of physics is that information about an event can be
gathered from a variety of reference frames. For example, imagine that
you are a passenger walking toward the front of a bus. As you walk, your
motion is observed by a fellow bus passenger and by an observer standing
on the sidewalk.

Both the bus passenger and sidewalk observer will be able to collect
information about you. They can determine how far you moved and how much
time it took you to do so. However, while you moved at a consistent
pace, both observers will get different results. To the passenger
sitting on the bus, you moved forward at what one would consider a
normal pace, something similar to how quickly you would walk outside on
a sunny day. To the sidewalk observer though, you will have moved much
quicker. Because the bus is also moving forward, the distance you move
forward against the sidewalk each second increases, and the sidewalk
observer must conclude that you are moving at a greater pace.

To show that you understand this concept, you will need to create an
event and think of a way to view this event from two different frames of
reference. In order to ensure that the event is being observed
simultaneously from both frames, you will need an assistant to help out.
An example of a possible event is to have a friend ride on a skateboard
while tossing a ball. How will your friend observe the ball toss, and
how will those observations be different from your own?

Your task is to describe your event and the observations of your event
from both frames of reference. Answer the following questions below to
demonstrate your understanding. For assistance, you can review the
information given in the 'Position\' paragraph at the start of Section
2.1.

1.  What is your event? What object are both you and your assistant
    observing?
2.  What do *you* see as the event takes place?
3.  What does *your assistant* see as the event takes place?
4.  How do your reference frames cause you and your assistant to have
    two different sets of observations?
:::

::: {#fs-id1368980 .ap-test-prep depth="1" element-type="ap-test-prep"}
### Test Prep for AP Courses { data-type="title"}

::: {#fs-id1890618 data-type="exercise" element-type="ap-test-prep"}
::: {#fs-id1408528 data-type="problem"}
A student is trying to determine the acceleration of a feather as she
drops it to the ground. If the student is looking to achieve a positive
velocity and positive acceleration, what is the *most sensible* way to
set up her coordinate system?

a.  Her hand should be a coordinate of zero and the upward direction
    should be considered positive.
b.  Her hand should be a coordinate of zero and the downward direction
    should be considered positive.
c.  The floor should be a coordinate of zero and the upward direction
    should be considered positive.
d.  The floor should be a coordinate of zero and the downward direction
    should be considered positive.
:::
:::
:::

::: {data-type="glossary"}
### Glossary { data-type="glossary-title"}

scalar
:   a quantity that is described by magnitude, but not direction

```{=html}
<!-- -->
```

vector
:   a quantity that is described by both magnitude and direction
:::