Time, Velocity, and Speed
-------------------------

![The motion of these racing snails can be described by their speeds and
their velocities. (credit: tobitasflickr,
Flickr)](images/Picture%206.png){#import-auto-id1690049}

::: {#fs-id1037368 .learning-objectives depth="1"}
### Learning Objectives { data-type="title"}

By the end of this section, you will be able to:

-   Explain the relationships between instantaneous velocity, average
    velocity, instantaneous speed, average speed, displacement, and
    time.
-   Calculate velocity and speed given initial position, initial time,
    final position, and final time.
-   Derive a graph of velocity vs. time given a graph of position vs.
    time.
-   Interpret a graph of velocity vs. time.

The information presented in this section supports the following AP®
learning objectives and science practices:

-   **3.A.1.1** The student is able to express the motion of an object
    using narrative, mathematical, and graphical representations.
    **(S.P. 1.5, 2.1, 2.2)**
-   **3.A.1.3** The student is able to analyze experimental data
    describing the motion of an object and is able to express the
    results of the analysis using narrative, mathematical, and graphical
    representations. **(S.P. 5.1)**
:::

There is more to motion than distance and displacement. Questions such
as, "How long does a foot race take?" and "What was the runner\'s
speed?" cannot be answered without an understanding of other concepts.
In this section we add definitions of time, velocity, and speed to
expand our description of motion.

::: {#fs-id1568419 depth="1"}
### Time {#time data-type="title"}

As discussed in [Physical Quantities and Units](/m54765), the most
fundamental physical quantities are defined by how they are measured.
This is the case with time. Every measurement of time involves measuring
a change in some physical quantity. It may be a number on a digital
clock, a heartbeat, or the position of the Sun in the sky. In physics,
the definition of time is simple---[time]{#import-auto-id2588516
data-type="term"} is *change*, or the interval over which change occurs.
It is impossible to know that time has passed unless something changes.

The amount of time or change is calibrated by comparison with a
standard. The SI unit for time is the second, abbreviated s. We might,
for example, observe that a certain pendulum makes one full swing every
0.75 s. We could then use the pendulum to measure time by counting its
swings or, of course, by connecting the pendulum to a clock mechanism
that registers time on a dial. This allows us to not only measure the
amount of time, but also to determine a sequence of events.

How does time relate to motion? We are usually interested in elapsed
time for a particular motion, such as how long it takes an airplane
passenger to get from his seat to the back of the plane. To find elapsed
time, we note the time at the beginning and end of the motion and
subtract the two. For example, a lecture may start at 11:00
[A.M.]{.smallcaps} and end at 11:50 [A.M.]{.smallcaps}, so that the
elapsed time would be 50 min. [Elapsed time]{#import-auto-id4083152
data-type="term"} **${\Delta t}{}$** is the difference between the
ending time and beginning time,

::: {#import-auto-id1757927 data-type="equation"}
$$\Delta t = {t_{f} - t_{0}},$$
:::

where ${\Delta t}{}$ is the change in time or elapsed time, $t_{f}{}$ is
the time at the end of the motion, and $t_{0}{}$ is the time at the
beginning of the motion. (As usual, the delta symbol, $\Delta{}$, means
the change in the quantity that follows it.)

Life is simpler if the beginning time $t_{0}{}$ is taken to be zero, as
when we use a stopwatch. If we were using a stopwatch, it would simply
read zero at the start of the lecture and 50 min at the end. If
$t_{0} = 0$, then ${\Delta t = t_{f}} \equiv t$.

In this text, for simplicity\'s sake,

-   [motion starts at time equal to zero
    ${({t_{0} = 0})}{}$]{#import-auto-id2571110}
-   [the symbol $t{}$ is used for elapsed time unless otherwise
    specified
    ${({{\Delta t = t_{f}} \equiv t})}{}$]{#import-auto-id4047929}
:::

::: {#fs-id1850777 depth="1"}
### Velocity {#velocity data-type="title"}

Your notion of velocity is probably the same as its scientific
definition. You know that if you have a large displacement in a small
amount of time you have a large velocity, and that velocity has units of
distance divided by time, such as miles per hour or kilometers per hour.

::: {#fs-id3597968 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Average Velocity
:::

[Average velocity]{#import-auto-id2596035 data-type="term"} is
*displacement (change in position) divided by the time of travel*,

::: {#import-auto-id4059844 data-type="equation"}
$${{{\overset{-}{v} = \frac{\Delta x}{\Delta t}} = \frac{x_{f} - x_{0}}{t_{f} - t_{0}}},}{}$$
:::

where $\overset{-}{v}{}$ is the *average* (indicated by the bar over the
$v{}$) velocity, ${\Delta x}{}$ is the change in position (or
displacement), and $x_{f}{}$ and $x_{0}$ are the final and beginning
positions at times $t_{f}$ and $t_{0}$, respectively. If the starting
time $t_{0}$ is taken to be zero, then the average velocity is simply

::: {#import-auto-id2027122 data-type="equation"}
$${{\overset{-}{v} = \frac{\Delta x}{t}}\text{.}}{}$$
:::
:::

Notice that this definition indicates that *velocity is a vector because
displacement is a vector*. It has both magnitude and direction. The SI
unit for velocity is meters per second or m/s, but many other units,
such as km/h, mi/h (also written as mph), and cm/s, are in common use.
Suppose, for example, an airplane passenger took 5 seconds to move −4 m
(the minus sign indicates that displacement is toward the back of the
plane). His average velocity would be

::: {#import-auto-id4051374 data-type="equation"}
$${{{\overset{-}{v} = \frac{\Delta x}{t}} = \frac{- 4\ \text{m}}{5\ \text{s}}} = - \text{0.8\ m/s.}}{}$$
:::

The minus sign indicates the average velocity is also toward the rear of
the plane.

The average velocity of an object does not tell us anything about what
happens to it between the starting point and ending point, however. For
example, we cannot tell from average velocity whether the airplane
passenger stops momentarily or backs up before he goes to the back of
the plane. To get more details, we must consider smaller segments of the
trip over smaller time intervals.

![A more detailed record of an airplane passenger heading toward the
back of the plane, showing smaller segments of his
trip.](images/Figure_02_02_01.jpg){#import-auto-id1782958}

The smaller the time intervals considered in a motion, the more detailed
the information. When we carry this process to its logical conclusion,
we are left with an infinitesimally small interval. Over such an
interval, the average velocity becomes the *instantaneous velocity*
*`<!-- no-selfclose -->`{=html}*or the *velocity at a specific instant*.
A car\'s speedometer, for example, shows the magnitude (but not the
direction) of the instantaneous velocity of the car. (Police give
tickets based on instantaneous velocity, but when calculating how long
it will take to get from one place to another on a road trip, you need
to use average velocity.) [Instantaneous
velocity]{#import-auto-id2579029 data-type="term"} $v{}$ is the average
velocity at a specific instant in time (or over an infinitesimally small
time interval).

Mathematically, finding instantaneous velocity, $v{}$, at a precise
instant $t{}$ can involve taking a limit, a calculus operation beyond
the scope of this text. However, under many circumstances, we can find
precise values for instantaneous velocity without calculus.
:::

::: {#fs-id3597726 depth="1"}
### Speed {#speed data-type="title"}

In everyday language, most people use the terms "speed" and "velocity"
interchangeably. In physics, however, they do not have the same meaning
and they are distinct concepts. One major difference is that speed has
no direction. Thus *speed is a scalar*. Just as we need to distinguish
between instantaneous velocity and average velocity, we also need to
distinguish between instantaneous speed and average speed.

[Instantaneous speed]{#import-auto-id2004213 data-type="term"} is the
magnitude of instantaneous velocity. For example, suppose the airplane
passenger at one instant had an instantaneous velocity of −3.0 m/s (the
minus meaning toward the rear of the plane). At that same time his
instantaneous speed was 3.0 m/s. Or suppose that at one time during a
shopping trip your instantaneous velocity is 40 km/h due north. Your
instantaneous speed at that instant would be 40 km/h---the same
magnitude but without a direction. Average speed, however, is very
different from average velocity. [Average speed]{#import-auto-id2004216
data-type="term"} is the distance traveled divided by elapsed time.

We have noted that distance traveled can be greater than displacement.
So average speed can be greater than average velocity, which is
displacement divided by time. For example, if you drive to a store and
return home in half an hour, and your car\'s odometer shows the total
distance traveled was 6 km, then your average speed was 12 km/h. Your
average velocity, however, was zero, because your displacement for the
round trip is zero. (Displacement is change in position and, thus, is
zero for a round trip.) Thus average speed is *not* simply the magnitude
of average velocity.

![During a 30-minute round trip to the store, the total distance
traveled is 6 km. The average speed is 12 km/h. The displacement for the
round trip is zero, since there was no net change in position. Thus the
average velocity is
zero.](images/Figure_02_02_02.jpg){#import-auto-id2593426}

Another way of visualizing the motion of an object is to use a graph. A
plot of position or of velocity as a function of time can be very
useful. For example, for this trip to the store, the position, velocity,
and speed-vs.-time graphs are displayed in
[link](#import-auto-id1806646){.autogenerated-content}. (Note that these
graphs depict a very simplified [model]{#import-auto-id1510828
data-type="term"} of the trip. We are assuming that speed is constant
during the trip, which is unrealistic given that we\'ll probably stop at
the store. But for simplicity\'s sake, we will model it with no stops or
changes in speed. We are also assuming that the route between the store
and the house is a perfectly straight line.)

![Position vs. time, velocity vs. time, and speed vs. time on a trip.
Note that the velocity for the return trip is
negative.](images/Figure_02_02_03.jpg){#import-auto-id1806646}

::: {#fs-id4030893 .note data-type="note" has-label="true" data-label=""}
::: {data-type="title"}
Making Connections: Take-Home Investigation---Getting a Sense of Speed
:::

If you have spent much time driving, you probably have a good sense of
speeds between about 10 and 70 miles per hour. But what are these in
meters per second? What do we mean when we say that something is moving
at 10 m/s? To get a better sense of what these values really mean, do
some observations and calculations on your own:

-   [calculate typical car speeds in meters per
    second]{#import-auto-id4058974}
-   [estimate jogging and walking speed by timing yourself; convert the
    measurements into both m/s and mi/h]{#import-auto-id4058977}
-   [determine the speed of an ant, snail, or falling
    leaf]{#import-auto-id4070923}
:::

::: {#fs-id4173641 data-type="exercise" element-type="check-understanding" data-label=""}
::: {data-type="title"}
Check Your Understanding
:::

::: {#fs-id1744684 data-type="problem"}
A commuter train travels from Baltimore to Washington, DC, and back in 1
hour and 45 minutes. The distance between the two stations is
approximately 40 miles. What is (a) the average velocity of the train,
and (b) the average speed of the train in m/s?
:::

::: {#fs-id1384034 data-type="solution"}
\(a\) The average velocity of the train is zero because
${x_{f} = x_{0}}{}$; the train ends up at the same place it starts.

\(b\) The average speed of the train is calculated below. Note that the
train travels 40 miles one way and 40 miles back, for a total distance
of 80 miles.

::: {#import-auto-id4070756 data-type="equation"}
$${\frac{\text{distance}}{\text{time}} = \frac{\text{80\ miles}}{\text{105\ minutes}}}{}$$
:::

::: {#import-auto-id1750086 data-type="equation"}
$${{{\frac{\text{80\ miles}}{\text{105\ minutes}} \times \frac{\text{5280\ feet}}{\text{1\ mile}}} \times \frac{\text{1\ meter}}{3\text{.}\text{28\ feet}}} \times \frac{\text{1\ minute}}{\text{60\ seconds}}} = \text{20\ m/s}$$
:::
:::
:::
:::

::: {#fs-id1345097-summary depth="1"}
### Section Summary { data-type="title"}

-   [Time is measured in terms of change, and its SI unit is the second
    (s). Elapsed time for an event is]{#import-auto-id4070541}
    ::: {#import-auto-id4146177 data-type="equation"}
    $${\Delta t = {t_{f} - t_{0}},}{}$$
    :::

    where $t_{f}{}$ is the final time and
    *`<!-- no-selfclose -->`{=html}*$t_{0}{}$ is the initial time. The
    initial time is often taken to be zero, as if measured with a
    stopwatch; the elapsed time is then just $t{}$.
-   [Average velocity $\overset{-}{v}{}$ is defined as displacement
    divided by the travel time. In symbols, average velocity
    is]{#import-auto-id1770783}
    ::: {#import-auto-id4086565 data-type="equation"}
    $${{{\overset{-}{v} = \frac{\Delta x}{\Delta t}} = \frac{x_{\text{f}} - x_{0}}{t_{\text{f}} - t_{0}}}\text{.}}{}$$
    :::
-   [The SI unit for velocity is m/s.]{#import-auto-id1795857}
-   [Velocity is a vector and thus has a
    direction.]{#import-auto-id1795847}
-   [Instantaneous velocity $v{}$ is the velocity at a specific instant
    or the average velocity for an infinitesimal
    interval.]{#import-auto-id4097170}
-   [Instantaneous speed is the magnitude of the instantaneous
    velocity.]{#import-auto-id4097153}
-   [Instantaneous speed is a scalar quantity, as it has no direction
    specified.]{#import-auto-id4097155}
-   [Average speed is the total distance traveled divided by the elapsed
    time. (Average speed is *not* the magnitude of the average
    velocity.) Speed is a scalar quantity; it has no direction
    associated with it.]{#import-auto-id4097159}
:::

::: {#fs-id3505230 .conceptual-questions depth="1" element-type="conceptual-questions"}
### Conceptual Questions { data-type="title"}

::: {#fs-id4081795 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id4057370 data-type="problem"}
Give an example (but not one from the text) of a device used to measure
time and identify what change in that device indicates a change in time.
:::
:::

::: {#fs-id4059976 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id4059193 data-type="problem"}
There is a distinction between average speed and the magnitude of
average velocity. Give an example that illustrates the difference
between these two quantities.
:::
:::

::: {#fs-id3539434 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1765012 data-type="problem"}
Does a car\'s odometer measure position or displacement? Does its
speedometer measure speed or velocity?
:::
:::

::: {#fs-id4033346 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id1181844 data-type="problem"}
If you divide the total distance traveled on a car trip (as determined
by the odometer) by the time for the trip, are you calculating the
average speed or the magnitude of the average velocity? Under what
circumstances are these two quantities the same?
:::
:::

::: {#fs-id1798382 data-type="exercise" element-type="conceptual-questions"}
::: {#fs-id3586650 data-type="problem"}
How are instantaneous velocity and instantaneous speed related to one
another? How do they differ?
:::
:::
:::

::: {#fs-id1644454 .problems-exercises depth="1" element-type="problems-exercises"}
### Problems & Exercises { data-type="title"}

::: {#fs-id4131776 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1489911 data-type="problem"}
\(a\) Calculate Earth\'s average speed relative to the Sun. (b) What is
its average velocity over a period of one year?
:::

::: {#fs-id3602083 data-type="solution"}
\(a\) ${3\text{.}{\text{0} \times \text{10}^{4}\ }\text{m/s}}{}$

\(b\) 0 m/s
:::
:::

::: {#fs-id3514248 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1773543 data-type="problem"}
A helicopter blade spins at exactly 100 revolutions per minute. Its tip
is 5.00 m from the center of rotation. (a) Calculate the average speed
of the blade tip in the helicopter\'s frame of reference. (b) What is
its average velocity over one revolution?
:::
:::

::: {#fs-id1438634 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1738040 data-type="problem"}
The North American and European continents are moving apart at a rate of
about 3 cm/y. At this rate how long will it take them to drift 500 km
farther apart than they are at present?
:::

::: {#fs-id2587370 data-type="solution"}
${{2 \times \text{10}^{7}}\ \text{years}}{}$
:::
:::

::: {#fs-id2572316 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1275687 data-type="problem"}
Land west of the San Andreas fault in southern California is moving at
an average velocity of about 6 cm/y northwest relative to land east of
the fault. Los Angeles is west of the fault and may thus someday be at
the same latitude as San Francisco, which is east of the fault. How far
in the future will this occur if the displacement to be made is 590 km
northwest, assuming the motion remains constant?
:::
:::

::: {#fs-id1403452 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1357553 data-type="problem"}
On May 26, 1934, a streamlined, stainless steel diesel train called the
Zephyr set the world\'s nonstop long-distance speed record for trains.
Its run from Denver to Chicago took 13 hours, 4 minutes, 58 seconds, and
was witnessed by more than a million people along the route. The total
distance traveled was 1633.8 km. What was its average speed in km/h and
m/s?
:::

::: {#fs-id4081588 data-type="solution"}
$\text{34}\text{.}\text{689\ m/s} = \text{124}\text{.}\text{88\ km/h}$
:::
:::

::: {#fs-id951583 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1535186 data-type="problem"}
Tidal friction is slowing the rotation of the Earth. As a result, the
orbit of the Moon is increasing in radius at a rate of approximately 4
cm/year. Assuming this to be a constant rate, how many years will pass
before the radius of the Moon\'s orbit increases by
${3\text{.}{\text{84} \times \text{10}^{6}}\ m}{}$ (1%)?
:::
:::

::: {#fs-id1271475 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1544659 data-type="problem"}
A student drove to the university from her home and noted that the
odometer reading of her car increased by 12.0 km. The trip took 18.0
min. (a) What was her average speed? (b) If the straight-line distance
from her home to the university is 10.3 km in a direction
${\text{25}\text{.}0º}{}$ south of east, what was her average velocity?
(c) If she returned home by the same path 7 h 30 min after she left,
what were her average speed and velocity for the entire trip?
:::

::: {#fs-id1780671 data-type="solution"}
\(a\) ${\text{40}\text{.}\text{0\ km/h}}{}$

\(b\) 34.3 km/h, ${\text{25º}\ \text{S\ of\ E}\text{.}}{}$

\(c\)
${{\text{average\ speed} = \text{3.20\ km/h,}\ \overset{-}{v}} = 0.}{}$
:::
:::

::: {#fs-id1644060 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id1742458 data-type="problem"}
The speed of propagation of the action potential (an electrical signal)
in a nerve cell depends (inversely) on the diameter of the axon (nerve
fiber). If the nerve cell connecting the spinal cord to your feet is 1.1
m long, and the nerve impulse speed is 18 m/s, how long does it take for
the nerve signal to travel this distance?
:::
:::

::: {#fs-id1638875 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id2015498 data-type="problem"}
Conversations with astronauts on the lunar surface were characterized by
a kind of echo in which the earthbound person\'s voice was so loud in
the astronaut\'s space helmet that it was picked up by the astronaut\'s
microphone and transmitted back to Earth. It is reasonable to assume
that the echo time equals the time necessary for the radio wave to
travel from the Earth to the Moon and back (that is, neglecting any time
delays in the electronic equipment). Calculate the distance from Earth
to the Moon given that the echo time was 2.56 s and that radio waves
travel at the speed of light
$(3\text{.}{\text{00} \times \text{10}^{8}\ }\text{m/s})$.
:::

::: {#fs-id1659453 data-type="solution"}
384,000 km
:::
:::

::: {#fs-id2577314 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id4044402 data-type="problem"}
A football quarterback runs 15.0 m straight down the playing field in
2.50 s. He is then hit and pushed 3.00 m straight backward in 1.75 s. He
breaks the tackle and runs straight forward another 21.0 m in 5.20 s.
Calculate his average velocity (a) for each of the three intervals and
(b) for the entire motion.
:::
:::

::: {#fs-id4047255 data-type="exercise" element-type="problems-exercises"}
::: {#fs-id4047256 data-type="problem"}
The planetary model of the atom pictures electrons orbiting the atomic
nucleus much as planets orbit the Sun. In this model you can view
hydrogen, the simplest atom, as having a single electron in a circular
orbit $1\text{.}\text{06} \times \text{10}^{- \text{10}}\ \text{m}$ in
diameter. (a) If the average speed of the electron in this orbit is
known to be $2\text{.}{\text{20} \times \text{10}^{6}}\ \text{m/s}$,
calculate the number of revolutions per second it makes about the
nucleus. (b) What is the electron\'s average velocity?
:::

::: {#fs-id2580487 data-type="solution"}
\(a\)
${6\text{.}{\text{61} \times \text{10}^{\text{15}}}\ \text{rev/s}}{}$

\(b\) 0 m/s
:::
:::
:::

::: {#fs-id1283687 .ap-test-prep depth="1" element-type="ap-test-prep"}
### Test Prep for AP Courses { data-type="title"}

::: {#fs-id2172989 data-type="exercise" element-type="ap-test-prep"}
::: {#fs-id2066649 data-type="problem"}
A group of students has two carts, *A* and *B*, with wheels that turn
with negligible friction. The two carts travel along a straight
horizontal track and eventually collide. Before the collision, cart *A*
travels to the right and cart *B* is initially at rest. After the
collision, the carts stick together.

a.  Describe an experimental procedure to determine the velocities of
    the carts before and after the collision, including all the
    additional equipment you would need. You may include a labeled
    diagram of your setup to help in your description. Indicate what
    measurements you would take and how you would take them. Include
    enough detail so that another student could carry out your
    procedure.
b.  There will be sources of error in the measurements taken in the
    experiment both before and after the collision. Which velocity will
    be more greatly affected by this error: the velocity prior to the
    collision or the velocity after the collision? Or will both sets of
    data be affected equally? Justify your answer.
:::

::: {#fs-id1336990 data-type="solution"}
a.  Use tape to mark off two distances on the track --- one for cart *A*
    before the collision and one for the combined carts after the
    collision. Push cart *A* to give it an initial speed. Use a
    stopwatch to measure the time it takes for the cart(s) to cross the
    marked distances. The speeds are the distances divided by the times.
b.  If the measurement errors are of the same magnitude, they will have
    a greater effect after the collision. The speed of the combined
    carts will be less than the initial speed of cart *A*. As a result,
    these errors will be a greater percentage of the actual velocity
    value after the collision occurs. (Note: Other arguments could
    properly be made for 'more error before the collision\' and error
    that 'equally affects both sets of measurement.\')
:::
:::
:::

::: {data-type="glossary"}
### Glossary { data-type="glossary-title"}

average speed
:   distance traveled divided by time during which motion occurs

```{=html}
<!-- -->
```

average velocity
:   displacement divided by time over which displacement occurs

```{=html}
<!-- -->
```

instantaneous velocity
:   velocity at a specific instant, or the average velocity over an
    infinitesimal time interval

```{=html}
<!-- -->
```

instantaneous speed
:   magnitude of the instantaneous velocity

```{=html}
<!-- -->
```

time
:   change, or the interval over which change occurs

```{=html}
<!-- -->
```

model
:   simplified description that contains only those elements necessary
    to describe the physics of a physical situation

```{=html}
<!-- -->
```

elapsed time
:   the difference between the ending time and beginning time
:::