# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.3.4
      # Runs a single command using the runners shell
      - name: Generate html, pdf and epub output
        run: Rscript generate_output.R

      # Runs a set of commands using the runners shell
      - name: update gh-pages branch
        run: |
          mv docs tmp
          git checkout gh-pages .
          rm -R docs
          mv tmp docs
          git add docs/*
          git commit -m "This commit comes from my bot"
          echo ${{secrets.GITHUB_TOKEN}} >token.txt
